/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * KarmaExchangePanel.java
 *
 * Created on Oct 14, 2009, 7:00:20 PM
 */

package org.karma.tools;
           
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import org.karma.helper.CompressExportDB;
import org.karma.helper.GenericLoadingDlg;
import org.karma.helper.KarmaTableCellRenderer;
import org.karma.helper.KarmaVaultHelp;

/**
 *
 * @author Manos
 */
public class KarmaExchangePanel extends javax.swing.JDialog {
public static final String[] columnNames = {"Karma Name", "Size"};
public static DefaultTableModel karmaTableModel;

    /** Creates new form KarmaExchangePanel */
    public KarmaExchangePanel(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        Dimension screenDim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation((screenDim.width-this.getWidth())/2,(screenDim.height-this.getHeight())/2);
         karmaTableModel = new DefaultTableModel(null,columnNames);
        KarmaList.setModel(karmaTableModel);

        //Set the size so it looks good
        TableColumn col = KarmaList.getColumnModel().getColumn(0);
        col.setPreferredWidth(KarmaList.getWidth()-(30/100)*KarmaList.getWidth());
        //Decorative things
        KarmaList.setShowHorizontalLines(false);
        KarmaList.setShowVerticalLines(true);
        KarmaList.setGridColor(Color.lightGray);
        KarmaList.setDefaultRenderer(Object.class, new KarmaTableCellRenderer());

          //Locate and pull list - also, check if KarmaVault is there
        if (!KarmaVaultHelp.checkKarmaDir()) { JOptionPane.showMessageDialog(null, "There was a problem with Karma Vault, check if there is a KarmaVault directory present and restart.", "", 1, new ImageIcon(super.getClass().getResource("warning.png")));}
        KarmaVaultHelp.getKarmas();
         System.out.println("A");
        for (int goThrough=0;goThrough<KarmaVaultHelp.getKarmas().length/2;goThrough++)
        {
            System.out.println("B");
        karmaTableModel.insertRow(goThrough,new Object[]{KarmaVaultHelp.getKarmas()[goThrough*2],KarmaVaultHelp.getKarmas()[(goThrough*2)+1]});

        }

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        jButton3 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        KarmaList = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);
        jToolBar1.add(jSeparator2);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/karma/tools/import.png"))); // NOI18N
        jButton1.setText(org.openide.util.NbBundle.getMessage(KarmaExchangePanel.class, "KarmaExchangePanel.jButton1.text")); // NOI18N
        jButton1.setBorderPainted(false);
        jButton1.setFocusable(false);
        jButton1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton1);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/karma/tools/import-web.png"))); // NOI18N
        jButton2.setMnemonic('W');
        jButton2.setText(org.openide.util.NbBundle.getMessage(KarmaExchangePanel.class, "KarmaExchangePanel.jButton2.text")); // NOI18N
        jButton2.setBorderPainted(false);
        jButton2.setFocusable(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton2);
        jToolBar1.add(jSeparator1);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/karma/tools/export.png"))); // NOI18N
        jButton3.setText(org.openide.util.NbBundle.getMessage(KarmaExchangePanel.class, "KarmaExchangePanel.jButton3.text")); // NOI18N
        jButton3.setBorder(null);
        jButton3.setFocusable(false);
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton3);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, org.openide.util.NbBundle.getMessage(KarmaExchangePanel.class, "KarmaExchangePanel.jPanel2.border.title"), javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 0, 12))); // NOI18N

        KarmaList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(KarmaList);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 387, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 399, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        chooser.setCurrentDirectory(new File("."));
        chooser.setDialogTitle("Export to...");
        chooser.setFileSelectionMode(1);
        chooser.setApproveButtonText("Export");
    if (chooser.showOpenDialog(this) == 0) {
        String chosen = this.KarmaList.getValueAt(this.KarmaList.getSelectedRow(), 0).toString();
        String exportDir = chooser.getSelectedFile().toString();
        GenericLoadingDlg GLDg = new GenericLoadingDlg(null,false,"Exporting...","");
        GLDg.setVisible(true);
        CompressExportDB CEDBZip = new CompressExportDB(chosen, exportDir, true,karmaTableModel,GLDg);
        CEDBZip.start();
    }

    //dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
     JFileChooser chooser = new JFileChooser();
    chooser.setCurrentDirectory(new File("."));
    chooser.setDialogTitle("Import Knowledge DB");
    chooser.setFileSelectionMode(0);
    chooser.setApproveButtonText("Import");
    if (chooser.showOpenDialog(this) != 0)
      return;
    String ImportZip = chooser.getSelectedFile().toString();
        GenericLoadingDlg GLDg = new GenericLoadingDlg(null,false,"Importing...","");
        GLDg.setVisible(true);
    
    CompressExportDB CEDBUnzip = new CompressExportDB("", ImportZip, false,karmaTableModel,GLDg);
    CEDBUnzip.start();

    //dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                KarmaExchangePanel dialog = new KarmaExchangePanel(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable KarmaList;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables

}
