package org.karma.metrics.javacc;
/* Generated By:JavaCC: Do not edit this line. CParserTreeConstants.java Version 5.0 */
public interface CParserTreeConstants
{
  public int JJTTRANSLATIONUNIT = 0;
  public int JJTEXTERNALDECLARATION = 1;
  public int JJTFUNCTIONDEFINITION = 2;
  public int JJTDECLARATION = 3;
  public int JJTDECLARATIONLIST = 4;
  public int JJTDECLARATIONSPECIFIERS = 5;
  public int JJTSTORAGECLASSSPECIFIER = 6;
  public int JJTTYPESPECIFIER = 7;
  public int JJTTYPEQUALIFIER = 8;
  public int JJTSTRUCTORUNIONSPECIFIER = 9;
  public int JJTSTRUCTORUNION = 10;
  public int JJTSTRUCTDECLARATIONLIST = 11;
  public int JJTINITDECLARATORLIST = 12;
  public int JJTINITDECLARATOR = 13;
  public int JJTSTRUCTDECLARATION = 14;
  public int JJTSPECIFIERQUALIFIERLIST = 15;
  public int JJTSTRUCTDECLARATORLIST = 16;
  public int JJTSTRUCTDECLARATOR = 17;
  public int JJTENUMSPECIFIER = 18;
  public int JJTENUMERATORLIST = 19;
  public int JJTENUMERATOR = 20;
  public int JJTDECLARATOR = 21;
  public int JJTDIRECTDECLARATOR = 22;
  public int JJTPOINTER = 23;
  public int JJTTYPEQUALIFIERLIST = 24;
  public int JJTPARAMETERTYPELIST = 25;
  public int JJTPARAMETERLIST = 26;
  public int JJTPARAMETERDECLARATION = 27;
  public int JJTIDENTIFIERLIST = 28;
  public int JJTINITIALIZER = 29;
  public int JJTINITIALIZERLIST = 30;
  public int JJTTYPENAME = 31;
  public int JJTABSTRACTDECLARATOR = 32;
  public int JJTDIRECTABSTRACTDECLARATOR = 33;
  public int JJTTYPEDEFNAME = 34;
  public int JJTSTATEMENT = 35;
  public int JJTLABELEDSTATEMENT = 36;
  public int JJTEXPRESSIONSTATEMENT = 37;
  public int JJTCOMPOUNDSTATEMENT = 38;
  public int JJTSTATEMENTLIST = 39;
  public int JJTSELECTIONSTATEMENT = 40;
  public int JJTITERATIONSTATEMENT = 41;
  public int JJTJUMPSTATEMENT = 42;
  public int JJTEXPRESSION = 43;
  public int JJTASSIGNMENTEXPRESSION = 44;
  public int JJTASSIGNMENTOPERATOR = 45;
  public int JJTCONDITIONALEXPRESSION = 46;
  public int JJTCONSTANTEXPRESSION = 47;
  public int JJTLOGICALOREXPRESSION = 48;
  public int JJTLOGICALANDEXPRESSION = 49;
  public int JJTINCLUSIVEOREXPRESSION = 50;
  public int JJTEXCLUSIVEOREXPRESSION = 51;
  public int JJTANDEXPRESSION = 52;
  public int JJTEQUALITYEXPRESSION = 53;
  public int JJTRELATIONALEXPRESSION = 54;
  public int JJTSHIFTEXPRESSION = 55;
  public int JJTADDITIVEEXPRESSION = 56;
  public int JJTMULTIPLICATIVEEXPRESSION = 57;
  public int JJTCASTEXPRESSION = 58;
  public int JJTUNARYEXPRESSION = 59;
  public int JJTUNARYOPERATOR = 60;
  public int JJTPOSTFIXEXPRESSION = 61;
  public int JJTPRIMARYEXPRESSION = 62;
  public int JJTARGUMENTEXPRESSIONLIST = 63;
  public int JJTCONSTANT = 64;


  public String[] jjtNodeName = {
    "TranslationUnit",
    "ExternalDeclaration",
    "FunctionDefinition",
    "Declaration",
    "DeclarationList",
    "DeclarationSpecifiers",
    "StorageClassSpecifier",
    "TypeSpecifier",
    "TypeQualifier",
    "StructOrUnionSpecifier",
    "StructOrUnion",
    "StructDeclarationList",
    "InitDeclaratorList",
    "InitDeclarator",
    "StructDeclaration",
    "SpecifierQualifierList",
    "StructDeclaratorList",
    "StructDeclarator",
    "EnumSpecifier",
    "EnumeratorList",
    "Enumerator",
    "Declarator",
    "DirectDeclarator",
    "Pointer",
    "TypeQualifierList",
    "ParameterTypeList",
    "ParameterList",
    "ParameterDeclaration",
    "IdentifierList",
    "Initializer",
    "InitializerList",
    "TypeName",
    "AbstractDeclarator",
    "DirectAbstractDeclarator",
    "TypedefName",
    "Statement",
    "LabeledStatement",
    "ExpressionStatement",
    "CompoundStatement",
    "StatementList",
    "SelectionStatement",
    "IterationStatement",
    "JumpStatement",
    "Expression",
    "AssignmentExpression",
    "AssignmentOperator",
    "ConditionalExpression",
    "ConstantExpression",
    "LogicalORExpression",
    "LogicalANDExpression",
    "InclusiveORExpression",
    "ExclusiveORExpression",
    "ANDExpression",
    "EqualityExpression",
    "RelationalExpression",
    "ShiftExpression",
    "AdditiveExpression",
    "MultiplicativeExpression",
    "CastExpression",
    "UnaryExpression",
    "UnaryOperator",
    "PostfixExpression",
    "PrimaryExpression",
    "ArgumentExpressionList",
    "Constant",
  };
}
/* JavaCC - OriginalChecksum=033d3277aa5bbf57e24d55dee05e1d8a (do not edit this line) */
