/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

package org.karma.metrics.javacc;

import java.io.FileNotFoundException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Manos
 */
public class metrics {


public int calculate (String file)
{       SimpleNode root = null;


         try {
           CParser parser = new CParser(new java.io.FileInputStream(file));
           
           
                    parser.TranslationUnit();
           // root.dump("");

        } catch (Exception ex) {
            Logger.getLogger(metrics.class.getName()).log(Level.SEVERE, null, ex);
        }

return 0;
  //return cyc( (SimpleNode) root.jjtGetChild(0) );
}





int cyc = 0;
    int cyc( SimpleNode node )
    //-------------------------
    {
        // each node contains an id field identifying its type.
        // we switch on these. we could use instanceof, but that's less efficient

        // enum values such as JJTINTLITERAL come from the interface file
        // SimpleParserTreeConstants, which SimpleParser implements.
        // This interface file is one of several auxilliary Java sources
        // generated by JJTree. JavaCC contributes several others.

        int id = node.id;


        SimpleNode lhs =  (SimpleNode) node.jjtGetChild(0);
        SimpleNode rhs =  (SimpleNode) node.jjtGetChild(1);

        switch( id )
        {
            case CParser.CASE :
            case CParser.IF :
            case CParser.ELSE :
            cyc++;

            default :

              break;
        }

        return cyc;
    }




    
}

