/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AddNewKarma.java
 *
 * Created on Aug 5, 2009, 11:34:29 PM
 */

package org.karma.trainer;

import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import org.karma.helper.ConsolePrint;


/**
 *
 * @author Manos
 */
public class AddNewKarma extends javax.swing.JDialog {

    /** Creates new form AddNewKarma */
    public AddNewKarma(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
         Dimension screenDim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation((screenDim.width-this.getWidth())/2,(screenDim.height-this.getHeight())/2);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        newKarma = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setModal(true);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        jLabel1.setText(org.openide.util.NbBundle.getMessage(AddNewKarma.class, "AddNewKarma.jLabel1.text_1")); // NOI18N

        newKarma.setFont(new java.awt.Font("Lucida Grande", 0, 11)); // NOI18N
        newKarma.setText(org.openide.util.NbBundle.getMessage(AddNewKarma.class, "AddNewKarma.newKarma.text_1")); // NOI18N

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/karma/trainer/1249511451_001_01.png"))); // NOI18N
        jButton1.setText(org.openide.util.NbBundle.getMessage(AddNewKarma.class, "AddNewKarma.jButton1.text_1")); // NOI18N
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(newKarma, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(newKarma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        boolean check = false;
        for (int goThrough=0;goThrough<TrainerPanel.karmaTableModel.getRowCount();goThrough++)
        if (TrainerPanel.karmaTableModel.getValueAt(goThrough,0).toString().equals(newKarma.getText()))
        {check =true;JOptionPane.showMessageDialog(null, "This name is already in use!", "", 1, new ImageIcon(super.getClass().getResource("warning.png")));}

        if (check!=true)
        {
        TrainerPanel.karmaTableModel.insertRow(TrainerPanel.karmaTableModel.getRowCount(),new Object[]{""+newKarma.getText(),"0 kb"});
        ConsolePrint.reportToConsole("Created a new untrained Karma : "+newKarma.getText());
        this.dispose();
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AddNewKarma dialog = new AddNewKarma(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField newKarma;
    // End of variables declaration//GEN-END:variables

}
