/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ControllerPanel.java
 *
 * Created on Aug 8, 2009, 6:09:39 PM
 */

package org.karma.trainer;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Toolkit;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import org.karma.helper.ConsolePrint;
import org.karma.helper.KarmaTableCellRenderer;
import org.karma.helper.KarmaVaultHelp;

/**
 *
 * @author Manos
 */
public class ControllerPanel extends javax.swing.JDialog {
public static final String[] columnNames = {"Karma Name", "Size"};
public static DefaultTableModel karmaTableModel;
    /** Creates new form ControllerPanel */
    public ControllerPanel(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
          karmaTableModel = new DefaultTableModel(null,columnNames){

            @Override
            public boolean isCellEditable(int row, int column) {
            return false;
            }
        };

        KarmaList.setModel(karmaTableModel);

        //Set the size so it looks good
        TableColumn col = KarmaList.getColumnModel().getColumn(0);
        col.setPreferredWidth(KarmaList.getWidth()-(30/100)*KarmaList.getWidth());
        //Decorative things
        KarmaList.setShowHorizontalLines(false);
        KarmaList.setShowVerticalLines(true);
        KarmaList.setGridColor(Color.lightGray);
        KarmaList.setDefaultRenderer(Object.class, new KarmaTableCellRenderer());

        //Locate and pull list - also, check if KarmaVault is there
        if (!KarmaVaultHelp.checkKarmaDir()) { JOptionPane.showMessageDialog(null, "There was a problem with Karma Vault, check if there is a KarmaVault directory present and restart.", "", 1, new ImageIcon(super.getClass().getResource("warning.png")));}
        KarmaVaultHelp.getKarmas();
        for (int goThrough=0;goThrough<KarmaVaultHelp.getKarmas().length/2;goThrough++)
        {
        karmaTableModel.insertRow(goThrough,new Object[]{KarmaVaultHelp.getKarmas()[goThrough*2],KarmaVaultHelp.getKarmas()[(goThrough*2)+1]});

        }
        Dimension screenDim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation((screenDim.width-this.getWidth())/2,(screenDim.height-this.getHeight())/2);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        jButton1 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        KarmaList = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);
        jToolBar1.add(jSeparator2);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/karma/trainer/1249752072_colorpicker.png"))); // NOI18N
        jButton1.setText(org.openide.util.NbBundle.getMessage(ControllerPanel.class, "ControllerPanel.jButton1.text")); // NOI18N
        jButton1.setBorder(null);
        jButton1.setFocusable(false);
        jButton1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton1);
        jToolBar1.add(jSeparator1);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/karma/trainer/bin.png"))); // NOI18N
        jButton2.setText(org.openide.util.NbBundle.getMessage(ControllerPanel.class, "ControllerPanel.jButton2.text")); // NOI18N
        jButton2.setBorder(null);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/karma/trainer/1249752537_document-properties.png"))); // NOI18N
        jButton3.setText(org.openide.util.NbBundle.getMessage(ControllerPanel.class, "ControllerPanel.jButton3.text")); // NOI18N
        jButton3.setBorder(null);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(116, Short.MAX_VALUE)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jToolBar1.add(jPanel1);

        KarmaList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        KarmaList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                KarmaListMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(KarmaList);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 428, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 428, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        String selection = (String) KarmaList.getValueAt(KarmaList.getSelectedRow(),0);

        String DialogKarmaChosen = "<HTML>You chose <b>"+selection+"</b>. <br>Do you want to go ahead and use it for this scan?</HTML>";
                    int userResponse = JOptionPane.showConfirmDialog(
                    this,  DialogKarmaChosen,"",
                    JOptionPane.YES_NO_OPTION,1,
                    new ImageIcon(super.getClass().getResource("good.png")));
if (userResponse==0)
{
        org.karma.helper.projectInfo.currentKarma = selection;
        net.sf.classifier4J.bayesian.JDBMWordsDataSource.databaseName = selection;
        ConsolePrint.reportToConsole("Selected Karma : "+selection);
        this.dispose();
}
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    //Just in case there is no selection, catch exception
         String psep = System.getProperty("file.separator");
    try {
    String selection = (String) KarmaList.getValueAt(KarmaList.getSelectedRow(),0);
     //org.karma.helper.KarmaVaultHelp.locateVault

    String warningLabelMsg = "<html>You are about to <font color=\"red\">delete</font> the <b>"+
                              selection+
                              "</b> Karma.<br>Are you sure?"+
                              "</html>";
        JLabel warningLabelDelete = new JLabel(warningLabelMsg);



          int userResponse = JOptionPane.showConfirmDialog(
                  this,  warningLabelDelete,"",
                    JOptionPane.YES_NO_OPTION,1,
                    new ImageIcon(super.getClass().getResource("warning.png")));
          if (userResponse ==0)
          {
          (new File(org.karma.helper.KarmaVaultHelp.locateVault+psep+selection+".lg")).delete();
          (new File(org.karma.helper.KarmaVaultHelp.locateVault+psep+selection+".db")).delete();

           for(int i=KarmaList.getRowCount();i>0;--i)
            karmaTableModel.removeRow(i-1);

          KarmaVaultHelp.getKarmas();
            for (int goThrough=0;goThrough<KarmaVaultHelp.getKarmas().length/2;goThrough++)
            {
                karmaTableModel.insertRow(goThrough,new Object[]{KarmaVaultHelp.getKarmas()[goThrough*2],KarmaVaultHelp.getKarmas()[(goThrough*2)+1]});
            }
          


          }

        }
    catch (ArrayIndexOutOfBoundsException e){}
       
    }//GEN-LAST:event_jButton2ActionPerformed

    private void KarmaListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_KarmaListMouseClicked
        // TODO add your handling code here:
        if(evt.getClickCount()==2){
        
                String selection = (String) KarmaList.getValueAt(KarmaList.getSelectedRow(),0);

                String DialogKarmaChosen = "<HTML>You chose <b>"+selection+"</b>. <br>Do you want to go ahead and use it for this scan?</HTML>";
                    int userResponse = JOptionPane.showConfirmDialog(
                    this,  DialogKarmaChosen,"",
                    JOptionPane.YES_NO_OPTION,1,
                    new ImageIcon(super.getClass().getResource("good.png")));
            if (userResponse==0)
            {
                    org.karma.helper.projectInfo.currentKarma = selection;
                    net.sf.classifier4J.bayesian.JDBMWordsDataSource.databaseName = selection;
                    ConsolePrint.reportToConsole("Selected Karma : "+selection);
                    this.dispose();

            }
    }
    }//GEN-LAST:event_KarmaListMouseClicked

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ControllerPanel dialog = new ControllerPanel(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable KarmaList;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables

}
