/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TrainerPanel.java
 *
 * Created on Jul 28, 2009, 8:46:17 PM
 */

package org.karma.trainer;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.File;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import org.karma.helper.ConsolePrint;
import org.karma.helper.ParseConfig;
import org.karma.helper.KarmaVaultHelp;
import org.karma.helper.KarmaTableCellRenderer;
import org.karma.trainer.TrainingWorker;
/**
 *
 * @author Manos
 */
public class TrainerPanel extends javax.swing.JDialog {
public static final String[] columnNames = {"Karma Name", "Size"};
public static DefaultTableModel karmaTableModel;
    /** Creates new form TrainerPanel */
    public TrainerPanel(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();


        karmaTableModel = new DefaultTableModel(null,columnNames);
        KarmaList.setModel(karmaTableModel);

        //Set the size so it looks good
        TableColumn col = KarmaList.getColumnModel().getColumn(0);
        col.setPreferredWidth(KarmaList.getWidth()-(30/100)*KarmaList.getWidth());
        //Decorative things
        KarmaList.setShowHorizontalLines(false);
        KarmaList.setShowVerticalLines(true);
        KarmaList.setGridColor(Color.lightGray);
        KarmaList.setDefaultRenderer(Object.class, new KarmaTableCellRenderer());

        //Locate and pull list - also, check if KarmaVault is there
        if (!KarmaVaultHelp.checkKarmaDir()) { JOptionPane.showMessageDialog(null, "There was a problem with Karma Vault, check if there is a KarmaVault directory present and restart.", "", 1, new ImageIcon(super.getClass().getResource("warning.png")));}
        KarmaVaultHelp.getKarmas();
        for (int goThrough=0;goThrough<KarmaVaultHelp.getKarmas().length/2;goThrough++)
        {
        karmaTableModel.insertRow(goThrough,new Object[]{KarmaVaultHelp.getKarmas()[goThrough*2],KarmaVaultHelp.getKarmas()[(goThrough*2)+1]});
        
        }
        

        StartTrain.setEnabled(false);
        Dimension screenDim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation((screenDim.width-this.getWidth())/2,(screenDim.height-this.getHeight())/2);
         ParseConfig.checkForConfig();
       if (!(ParseConfig.checkForNeeded())) { JOptionPane.showMessageDialog(null, "There was a problem with the config file, within the Configuration panel\nreview, save and restart Karma.\n\nIf the problem persists, remove \"KarmaHam.config\" and restart.", "", 1, new ImageIcon(super.getClass().getResource("warning.png")));}

       ArrayList LanguageItems = ParseConfig.extractLanguageAndExtension();
         for (int a = 0; a < LanguageItems.size(); ++a)
            {
            String[] itemsToAdd = LanguageItems.get(a).toString().split("=");
            if (itemsToAdd.length != 2) continue; Language.addItem(itemsToAdd[0].trim());
            }

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        StartTrain = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        PatchBase = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        Language = new javax.swing.JComboBox();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        KarmaList = new javax.swing.JTable();
        TrainingProgress = new javax.swing.JProgressBar();
        jLabel1 = new javax.swing.JLabel();
        PatchExtensions = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);
        jToolBar1.add(jSeparator2);

        StartTrain.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/karma/trainer/1248811467_quick_restart.png"))); // NOI18N
        StartTrain.setText(org.openide.util.NbBundle.getMessage(TrainerPanel.class, "TrainerPanel.StartTrain.text")); // NOI18N
        StartTrain.setBorder(null);
        StartTrain.setFocusable(false);
        StartTrain.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        StartTrain.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        StartTrain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StartTrainActionPerformed(evt);
            }
        });
        jToolBar1.add(StartTrain);
        jToolBar1.add(jSeparator1);

        PatchBase.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/karma/trainer/1248812071_Folder_01.png"))); // NOI18N
        PatchBase.setText(org.openide.util.NbBundle.getMessage(TrainerPanel.class, "TrainerPanel.PatchBase.text")); // NOI18N
        PatchBase.setBorder(null);
        PatchBase.setFocusable(false);
        PatchBase.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        PatchBase.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        PatchBase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PatchBaseActionPerformed(evt);
            }
        });
        jToolBar1.add(PatchBase);
        jToolBar1.add(jSeparator3);

        Language.setFont(new java.awt.Font("Lucida Grande", 0, 11));
        Language.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Choose Language" }));
        Language.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LanguageActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, org.openide.util.NbBundle.getMessage(TrainerPanel.class, "TrainerPanel.jPanel1.border.title"), javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 0, 12))); // NOI18N

        KarmaList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        KarmaList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                KarmaListMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(KarmaList);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        TrainingProgress.setStringPainted(true);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 12));
        jLabel1.setText(org.openide.util.NbBundle.getMessage(TrainerPanel.class, "TrainerPanel.jLabel1.text")); // NOI18N

        PatchExtensions.setFont(new java.awt.Font("Lucida Grande", 0, 11));
        PatchExtensions.setText(org.openide.util.NbBundle.getMessage(TrainerPanel.class, "TrainerPanel.PatchExtensions.text")); // NOI18N

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 12));
        jLabel2.setText(org.openide.util.NbBundle.getMessage(TrainerPanel.class, "TrainerPanel.jLabel2.text")); // NOI18N

        jButton3.setFont(new java.awt.Font("Lucida Grande", 0, 11));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/karma/trainer/1248813395_label_new red.png"))); // NOI18N
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        jButton3.setLabel(org.openide.util.NbBundle.getMessage(TrainerPanel.class, "TrainerPanel.jButton3.label")); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/karma/trainer/1248813899_left_48.png"))); // NOI18N
        jLabel3.setText(org.openide.util.NbBundle.getMessage(TrainerPanel.class, "TrainerPanel.jLabel3.text")); // NOI18N

        jLabel4.setText(org.openide.util.NbBundle.getMessage(TrainerPanel.class, "TrainerPanel.jLabel4.text")); // NOI18N

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 0, 11));
        jLabel5.setText(org.openide.util.NbBundle.getMessage(TrainerPanel.class, "TrainerPanel.jLabel5.text")); // NOI18N

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 0, 11));
        jLabel6.setText(org.openide.util.NbBundle.getMessage(TrainerPanel.class, "TrainerPanel.jLabel6.text")); // NOI18N

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 0, 11));
        jLabel7.setText(org.openide.util.NbBundle.getMessage(TrainerPanel.class, "TrainerPanel.jLabel7.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 533, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel2)
                        .addComponent(jLabel1)
                        .addComponent(Language, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(PatchExtensions, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5)
                                .addComponent(jLabel4)
                                .addComponent(jLabel6)
                                .addComponent(jLabel7))
                            .addGap(42, 42, 42))))
                .addContainerGap(6, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TrainingProgress, javax.swing.GroupLayout.DEFAULT_SIZE, 521, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Language, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PatchExtensions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4))
                                .addGap(0, 0, 0)
                                .addComponent(jLabel6)
                                .addGap(0, 0, 0)
                                .addComponent(jLabel7)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TrainingProgress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PatchBaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PatchBaseActionPerformed
        // TODO add your handling code here:
                // TODO add your handling code here:

        JFileChooser chooser = new JFileChooser();
        chooser.setCurrentDirectory(new File("."));
        chooser.setDialogTitle("Pick Source Base Directory");
        chooser.setFileSelectionMode(1);
        chooser.setAcceptAllFileFilterUsed(false);

    if (chooser.showOpenDialog(this) == 0)
    {
      PatchBase.setToolTipText(chooser.getSelectedFile() + "");
      ConsolePrint.reportToConsole("Trainer will learn from :"+chooser.getSelectedFile() + "");
      StartTrain.setEnabled(true);
    }
        
    }//GEN-LAST:event_PatchBaseActionPerformed

    private void StartTrainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartTrainActionPerformed
        // TODO add your handling code here:
         if (KarmaList.getSelectedColumn()==-1 ||
             Language.getSelectedItem().toString().equalsIgnoreCase("Choose Language") ||
             PatchBase.getToolTipText().equals(""))

        {
             JOptionPane.showMessageDialog(null,
                 "You probably forgot one of the following : \n" +
                 "- Set Language\n" +
                 "- Choose a patch directory\n" +
                 "- Select a Karma to train\n",
                 "", 1, new ImageIcon(super.getClass().getResource("warning.png")));
         }
         else
         {
              StartTrain.setEnabled(false);
              String selectedKarma = (String) KarmaList.getValueAt(KarmaList.getSelectedRow(),0);
              ConsolePrint.reportToConsole("Karma is Training");
              TrainingProgress.setValue(0);
              TrainingWorker TW = new  TrainingWorker(
                      PatchBase.getToolTipText(),
                      PatchExtensions.getText(),
                      Language.getSelectedItem().toString(),
                      selectedKarma,
                      TrainingProgress,
                      StartTrain,
                      KarmaList,
                      karmaTableModel);
              TW.start();
         }

    }//GEN-LAST:event_StartTrainActionPerformed

    private void KarmaListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_KarmaListMouseClicked
        // TODO add your handling code here:
        String selection = (String) KarmaList.getValueAt(KarmaList.getSelectedRow(),0);
        ConsolePrint.reportToConsole("Selected Karma to be trained : "+selection);
        
    }//GEN-LAST:event_KarmaListMouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        (new AddNewKarma(null,true)).setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void LanguageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LanguageActionPerformed
        // TODO add your handling code here:
        ConsolePrint.reportToConsole("Trainer will teach :"+Language.getSelectedItem().toString() + "");
    }//GEN-LAST:event_LanguageActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TrainerPanel dialog = new TrainerPanel(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTable KarmaList;
    public static javax.swing.JComboBox Language;
    private javax.swing.JButton PatchBase;
    private javax.swing.JTextField PatchExtensions;
    private javax.swing.JButton StartTrain;
    private javax.swing.JProgressBar TrainingProgress;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables

}
