/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * setDoxygenPanel.java
 *
 * Created on Jun 1, 2013, 9:34:53 PM
 */
package org.karma.helper;

import java.awt.Dimension;
import java.awt.Toolkit;

import java.io.*;
import javax.swing.JFileChooser;
import org.apache.commons.io.FileUtils;


/**
 *
 * @author Manos
 */


public class setDoxygenPanel extends javax.swing.JDialog {

final static String whereAMI = ""+KarmaVaultHelp.class.getProtectionDomain().getCodeSource().getLocation().getPath();
final static String RootDir =new File(whereAMI.substring(whereAMI.indexOf(System.getProperty("file.separator")))).getParent()+System.getProperty("file.separator")+".."+System.getProperty("file.separator")+"Doxygen.config";


    /** Creates new form setDoxygenPanel */
    public setDoxygenPanel(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        Dimension screenDim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation((screenDim.width-this.getWidth())/2,(screenDim.height-this.getHeight())/2);
        
         try
        {
            BufferedReader in = new BufferedReader(new FileReader(RootDir));
          do
            {  
                String str;
                str = in.readLine();
                if(str==null)
                {
                    enableDoxygen.setSelected(false);
                    projectInfo.isDoxygenOn = false;
                    break;
                }
                else 
                {
                    pathToDoxygen.setText(str);
                    enableDoxygen.setSelected(true);
                    projectInfo.isDoxygenOn = true;
                    projectInfo.DoxygenPath = str;
                    break;
                }

            } while(true);
           in.close();
            
            
            
        }
         catch(IOException e)
        {
            System.out.println(""+e);
         enableDoxygen.setSelected(false);
         projectInfo.isDoxygenOn = false;
        }
         
         
        
        
        
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pathToDoxygen = new javax.swing.JTextField();
        enableDoxygen = new javax.swing.JCheckBox();
        choosePath = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(org.openide.util.NbBundle.getMessage(setDoxygenPanel.class, "setDoxygenPanel.title")); // NOI18N

        pathToDoxygen.setFont(pathToDoxygen.getFont().deriveFont(pathToDoxygen.getFont().getSize()-2f));
        pathToDoxygen.setText(org.openide.util.NbBundle.getMessage(setDoxygenPanel.class, "setDoxygenPanel.pathToDoxygen.text")); // NOI18N

        enableDoxygen.setFont(enableDoxygen.getFont().deriveFont(enableDoxygen.getFont().getSize()-2f));
        enableDoxygen.setText(org.openide.util.NbBundle.getMessage(setDoxygenPanel.class, "setDoxygenPanel.enableDoxygen.text")); // NOI18N
        enableDoxygen.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                enableDoxygenStateChanged(evt);
            }
        });
        enableDoxygen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enableDoxygenActionPerformed(evt);
            }
        });

        choosePath.setFont(choosePath.getFont().deriveFont(choosePath.getFont().getSize()-2f));
        choosePath.setText(org.openide.util.NbBundle.getMessage(setDoxygenPanel.class, "setDoxygenPanel.choosePath.text")); // NOI18N
        choosePath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                choosePathActionPerformed(evt);
            }
        });

        jLabel1.setFont(jLabel1.getFont().deriveFont(jLabel1.getFont().getSize()-2f));
        jLabel1.setText(org.openide.util.NbBundle.getMessage(setDoxygenPanel.class, "setDoxygenPanel.jLabel1.text")); // NOI18N

        jLabel2.setFont(jLabel2.getFont().deriveFont(jLabel2.getFont().getSize()-2f));
        jLabel2.setText(org.openide.util.NbBundle.getMessage(setDoxygenPanel.class, "setDoxygenPanel.jLabel2.text")); // NOI18N

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .addContainerGap()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(layout.createSequentialGroup()
                                .add(enableDoxygen)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(pathToDoxygen)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                .add(choosePath))
                            .add(jLabel1)))
                    .add(layout.createSequentialGroup()
                        .add(83, 83, 83)
                        .add(jLabel2)))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(pathToDoxygen, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(enableDoxygen)
                    .add(choosePath))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabel1)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabel2)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void choosePathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_choosePathActionPerformed
        // TODO add your handling code here:
        
        JFileChooser chooser = new JFileChooser();
        //chooser.setCurrentDirectory(new java.io.File("."));
        chooser.setDialogTitle("choosertitle");
        chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        chooser.setAcceptAllFileFilterUsed(false);

        if (chooser.showOpenDialog(null) == JFileChooser.APPROVE_OPTION) {
        //System.out.println("getCurrentDirectory(): " + chooser.getCurrentDirectory());
        //System.out.println("getSelectedFile() : " + chooser.getSelectedFile());
        pathToDoxygen.setText(chooser.getSelectedFile()+"");
        enableDoxygen.setSelected(false);
        
        
        } else 
        {
        System.out.println("No Selection ");
        }


    }//GEN-LAST:event_choosePathActionPerformed

    private void enableDoxygenStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_enableDoxygenStateChanged
        // TODO add your handling code here:
       File config = new File(RootDir);
        if (enableDoxygen.isSelected())
        {   String thePathText = pathToDoxygen.getText();
            try
            {
                FileUtils.writeStringToFile(config, thePathText);
                projectInfo.isDoxygenOn = true;
            }
            catch(IOException ex) 
            {System.out.println(ex); }
        }
        else
        {
            try
            {   projectInfo.isDoxygenOn = false;
                config.delete();
            }
            catch(Exception ex) 
            {System.out.println(ex); }
        }
        
        
        
       
    }//GEN-LAST:event_enableDoxygenStateChanged

    private void enableDoxygenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enableDoxygenActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_enableDoxygenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                setDoxygenPanel dialog = new setDoxygenPanel(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton choosePath;
    private javax.swing.JCheckBox enableDoxygen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField pathToDoxygen;
    // End of variables declaration//GEN-END:variables
}
