/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CodeSearchDlg.java
 *
 * Created on May 27, 2010, 12:09:35 PM
 */

package org.karma.asearch;

import java.awt.Dimension;
import static java.awt.EventQueue.invokeLater;
import java.awt.Toolkit;
import static java.awt.Toolkit.getDefaultToolkit;
import static java.lang.System.exit;
import static java.lang.System.out;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.event.HyperlinkEvent;
import static javax.swing.event.HyperlinkEvent.EventType.ACTIVATED;
import javax.swing.event.HyperlinkListener;
import javax.swing.table.DefaultTableModel;
import static org.karma.helper.GlobalComponents.buglist;
import static org.karma.helper.SignatureConfig.extractLanguageAndExtension;
import static org.karma.helper.projectInfo.base;
import org.karma.helper.searchJTree;




/**
 *
 * @author Manos
 */
public class CodeSearchDlg extends javax.swing.JDialog implements HyperlinkListener {
 public static final String[] columnNames = {"Score", "File","Snip"};
 public static DefaultTableModel bugsTableModel;

    /** Creates new form CodeSearchDlg
     * @param parent
     * @param modal */
    public CodeSearchDlg(java.awt.Frame parent, boolean modal) {
        super(parent, false);

        initComponents();
        this.getRootPane().setDefaultButton(Find);
        this.setAlwaysOnTop(true);
        Dimension screenDim = getDefaultToolkit().getScreenSize();
        this.setLocation((screenDim.width-this.getWidth())/2,(screenDim.height-this.getHeight())/2);
        SearchOutput.addHyperlinkListener(this);
        //org.karma.helper.SignatureConfig.extractLanguageAndExtension()
        SearchOutput.setContentType("text/html");
        SearchOutput.setText("<br><center><img src=\"" + super.getClass().getResource("asearch.png") + "\"></center>");

        ArrayList signatureMap = extractLanguageAndExtension();
        String[] samples = new String[signatureMap.size()];
        if (samples.length==0) {samples = new String[1];}
        samples[0]="";
        out.println("---->"+signatureMap.size());
         for (int i = 0; i < signatureMap.size(); ++i)
            {
             try
             {
                     samples[i+1] = signatureMap.get(i).toString();

             }
             catch(Exception e){}
            }

           //SearchField
           DefaultComboBoxModel    sampleM = new DefaultComboBoxModel(samples);
           SearchField.setModel(sampleM);


    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Find = new javax.swing.JButton();
        SearchField = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        SearchOutput = new javax.swing.JEditorPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(CodeSearchDlg.class, "CodeSearchDlg.jPanel1.border.title"))); // NOI18N

        Find.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/karma/asearch/1274959332_001_38.gif"))); // NOI18N
        Find.setText(org.openide.util.NbBundle.getMessage(CodeSearchDlg.class, "CodeSearchDlg.Find.text")); // NOI18N
        Find.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FindActionPerformed(evt);
            }
        });

        SearchField.setEditable(true);
        SearchField.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        SearchField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchFieldActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                .add(SearchField, 0, 444, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(Find))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(SearchField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(Find))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        SearchOutput.setContentType(org.openide.util.NbBundle.getMessage(CodeSearchDlg.class, "CodeSearchDlg.SearchOutput.contentType")); // NOI18N
        SearchOutput.setEditable(false);
        jScrollPane1.setViewportView(SearchOutput);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 540, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 66, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
SearchFiles SFiles;
    private void FindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FindActionPerformed
        // TODO add your handling code here:
        
        SearchFiles.doit(SearchField,SearchOutput);
     try{   
      if(SFiles == null)
      {
        SFiles = new SearchFiles(SearchField,SearchOutput);
        SFiles.start();
      }
       else if (!SFiles.isAlive())
        {
        SFiles = new SearchFiles(SearchField,SearchOutput);
        SFiles.start();
        }
    }
    catch(Exception e){System.out.println(e);}
            
        
    }//GEN-LAST:event_FindActionPerformed

    private void SearchFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchFieldActionPerformed
        // TODO add your handling code here:
      /*  
      try
      {
      if(SFiles == null)
      {
        SFiles = new SearchFiles(SearchField,SearchOutput);
        SFiles.start();
      }
       else if (!SFiles.isAlive())
        {
        SFiles = new SearchFiles(SearchField,SearchOutput);
        SFiles.start();
        }
      }
      catch(Exception e){}
      
      */
    }//GEN-LAST:event_SearchFieldActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        invokeLater(() -> {
            CodeSearchDlg dialog = new CodeSearchDlg(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Find;
    public static javax.swing.JComboBox SearchField;
    public static javax.swing.JEditorPane SearchOutput;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

 @Override
    public void hyperlinkUpdate(HyperlinkEvent he) {
        if (he.getEventType() == ACTIVATED) {
      try {

          String fullpathto =he.getURL().toString().substring(4).substring(base.length()+1);
          //System.out.println(""+fullpathto);
                            searchJTree sJT = new searchJTree();
                            sJT.selectNode(sJT.doit(buglist,fullpathto), buglist);
                            
          
      } catch(Exception ioe) {
        // Some warning to user
      }
    }
    }

}
