/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AddDefinitionDlg.java
 *
 * Created on May 31, 2011, 6:40:20 PM
 */

package FlowDiags;

import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Manos
 */
public class AddDefinitionDlg extends javax.swing.JDialog {

    /** Creates new form AddDefinitionDlg
     * @param parent
     * @param modal
     * @param definitionFor */
    public AddDefinitionDlg(java.awt.Frame parent, boolean modal,String definitionFor) {
        super(parent, false);
        this.setAlwaysOnTop(true);
        final Toolkit toolkit = Toolkit.getDefaultToolkit();
        final Dimension screenSize = toolkit.getScreenSize();
        final int x = (screenSize.width - this.getWidth()) / 2;
        final int y = (screenSize.height - this.getHeight()) / 2;
        this.setLocation(x, y);
        //this.setVisible(true);
        initComponents();
        if (!definitionFor.equals(""))
        {DefText.setText(definitionFor);}
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        DefText = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        DefTextArea = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        addDef = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(296, 298));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, org.openide.util.NbBundle.getMessage(AddDefinitionDlg.class, "AddDefinitionDlg.jPanel1.border.title"), javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 0, 12))); // NOI18N
        jPanel1.setFont(new java.awt.Font("Lucida Grande", 0, 1));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 12));
        jLabel1.setText(org.openide.util.NbBundle.getMessage(AddDefinitionDlg.class, "AddDefinitionDlg.jLabel1.text")); // NOI18N

        DefText.setFont(new java.awt.Font("Lucida Grande", 0, 11)); // NOI18N
        DefText.setText(org.openide.util.NbBundle.getMessage(AddDefinitionDlg.class, "AddDefinitionDlg.DefText.text")); // NOI18N
        DefText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DefTextActionPerformed(evt);
            }
        });

        DefTextArea.setColumns(20);
        DefTextArea.setRows(5);
        jScrollPane1.setViewportView(DefTextArea);

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 12));
        jLabel2.setText(org.openide.util.NbBundle.getMessage(AddDefinitionDlg.class, "AddDefinitionDlg.jLabel2.text")); // NOI18N

        addDef.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FlowDiags/separator_grey.png"))); // NOI18N
        addDef.setText(org.openide.util.NbBundle.getMessage(AddDefinitionDlg.class, "AddDefinitionDlg.addDef.text")); // NOI18N
        addDef.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDefActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, addDef)
                    .add(jLabel2)
                    .add(jLabel1)
                    .add(DefText, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(jLabel1)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(DefText, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(9, 9, 9)
                .add(jLabel2)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(addDef))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DefTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DefTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DefTextActionPerformed

    private void addDefActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDefActionPerformed
        // TODO add your handling code here:

       ((DefaultTableModel)(FlowNotesTopComponent.FlowDefinition.getModel()))
                  .insertRow(0, new Object[]{DefText.getText(),DefTextArea.getText()});
        this.dispose();


    }//GEN-LAST:event_addDefActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField DefText;
    public static javax.swing.JTextArea DefTextArea;
    public static javax.swing.JButton addDef;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

}
