/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package FlowDiags;

import java.awt.Color;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.util.LinkedHashMap;
import java.util.logging.Logger;
import javax.swing.JEditorPane;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import javax.swing.text.Document;
import org.karma.helper.DesEncrypter;
import org.karma.helper.KarmaTableCellRenderer;
import org.karma.helper.searchJTree;
import org.karma.visual.ManualFlowGraph;
import org.netbeans.api.settings.ConvertAsProperties;
import org.openide.util.Exceptions;
import org.openide.util.ImageUtilities;
import org.openide.util.NbBundle;
import org.openide.windows.TopComponent;
import org.openide.windows.WindowManager;

/**
 * Top component which displays something.
 */
@ConvertAsProperties(dtd = "-//FlowDiags//FlowNotes//EN",
autostore = false)
public final class FlowNotesTopComponent extends TopComponent {
public static JEditorPane receivingCode=null;


public static final String[] columnNames = {"Line No", "Code Snippet","File"};
public static final String[] columnNamesDef = {"Definition", "Code"};
   public static DefaultTableModel flowTableModel,flowTableModelDef;


    public static FlowNotesTopComponent instance;
    /** path to the icon used by the component and its open action */
    static final String ICON_PATH = "FlowDiags/note.gif";
    private static final String PREFERRED_ID = "FlowNotesTopComponent";

    public FlowNotesTopComponent() {
        initComponents();
        setName(NbBundle.getMessage(FlowNotesTopComponent.class, "CTL_FlowNotesTopComponent"));
        setToolTipText(NbBundle.getMessage(FlowNotesTopComponent.class, "HINT_FlowNotesTopComponent"));
        setIcon(ImageUtilities.loadImage(ICON_PATH, true));
        putClientProperty(TopComponent.PROP_MAXIMIZATION_DISABLED, Boolean.TRUE);
        putClientProperty(TopComponent.PROP_KEEP_PREFERRED_SIZE_WHEN_SLIDED_IN, Boolean.TRUE);


         flowTableModel = new DefaultTableModel(new Object[0][0][0],columnNames)
        {@Override
        public boolean isCellEditable(int row, int col) {return false;}};

          flowTableModelDef = new DefaultTableModel(new Object[0][0],columnNamesDef)
        {@Override
        public boolean isCellEditable(int row, int col) {return false;}};

        Flow.setModel(flowTableModel);
        FlowDefinition.setModel(flowTableModelDef);
        //Set the size so it looks good
        TableColumn colLine = Flow.getColumnModel().getColumn(0);
        colLine.setPreferredWidth(50);
        colLine.setMaxWidth(200);
        TableColumn colConfidence = Flow.getColumnModel().getColumn(2);
        colConfidence.setPreferredWidth(100);
        colConfidence.setMaxWidth(200);
        //Decorative things
        Flow.setShowHorizontalLines(false);
        Flow.setShowVerticalLines(true);
        Flow.setGridColor(Color.lightGray);
        KarmaTableCellRenderer KTCR = new KarmaTableCellRenderer();
        Flow.setDefaultRenderer(Object.class, new KarmaTableCellRenderer());
        for (int a=0;a<30;a++)
        flowTableModel.insertRow(Flow.getRowCount(),new Object[]{""});


        //Set the size so it looks good
        TableColumn colLineDef = FlowDefinition.getColumnModel().getColumn(0);
        colLineDef.setPreferredWidth(50);
        colLineDef.setMaxWidth(200);
        TableColumn colConfidenceDefCode = FlowDefinition.getColumnModel().getColumn(1);
        colConfidenceDefCode.setPreferredWidth(100);
        colConfidenceDefCode.setMaxWidth(300);
        //Decorative things
        FlowDefinition.setShowHorizontalLines(false);
        FlowDefinition.setShowVerticalLines(true);
        FlowDefinition.setGridColor(Color.lightGray);
        FlowDefinition.setDefaultRenderer(Object.class, new KarmaTableCellRenderer());
        for (int a=0;a<30;a++)
        flowTableModelDef.insertRow(FlowDefinition.getRowCount(),new Object[]{""});


    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Flow = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        FlowDefinition = new javax.swing.JTable();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();

        Flow.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Flow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FlowMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Flow);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FlowDiags/separator_grey.png"))); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(jButton1, org.openide.util.NbBundle.getMessage(FlowNotesTopComponent.class, "FlowNotesTopComponent.jButton1.text")); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FlowDiags/action-delete-sharp-thick.png"))); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(jButton2, org.openide.util.NbBundle.getMessage(FlowNotesTopComponent.class, "FlowNotesTopComponent.jButton2.text")); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FlowDiags/save.png"))); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(jButton3, org.openide.util.NbBundle.getMessage(FlowNotesTopComponent.class, "FlowNotesTopComponent.jButton3.text")); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FlowDiags/import.gif"))); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(jButton4, org.openide.util.NbBundle.getMessage(FlowNotesTopComponent.class, "FlowNotesTopComponent.jButton4.text")); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FlowDiags/note.gif"))); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(jButton5, org.openide.util.NbBundle.getMessage(FlowNotesTopComponent.class, "FlowNotesTopComponent.jButton5.text")); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        FlowDefinition.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(FlowDefinition);

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FlowDiags/action-delete-sharp-thick.png"))); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(jButton6, org.openide.util.NbBundle.getMessage(FlowNotesTopComponent.class, "FlowNotesTopComponent.jButton6.text")); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setIcon(new javax.swing.ImageIcon("/Users/Manos/Downloads/icon_info.png")); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(jButton7, org.openide.util.NbBundle.getMessage(FlowNotesTopComponent.class, "FlowNotesTopComponent.jButton7.text")); // NOI18N
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jButton3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                .add(19, 19, 19)
                .add(jButton5)
                .add(18, 18, 18)
                .add(jButton4)
                .addContainerGap())
            .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 353, Short.MAX_VALUE)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jScrollPane2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 353, Short.MAX_VALUE)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jButton7, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 75, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 139, Short.MAX_VALUE)
                .add(jButton6)
                .addContainerGap())
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jButton1)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 90, Short.MAX_VALUE)
                .add(jButton2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 128, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.CENTER)
                    .add(jButton4)
                    .add(jButton3)
                    .add(jButton5))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jButton2)
                    .add(jButton1))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jScrollPane2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 115, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jButton6)
                    .add(jButton7)))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
 try { ((DefaultTableModel)(Flow.getModel())).removeRow(Flow.getSelectedRow());}
 catch(Exception e){}
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

          int result = JOptionPane.showConfirmDialog(null, "This will clear both Flow Notes and Definitions!", "Warning",JOptionPane.ERROR_MESSAGE);
        if (result==0)
        {
         DefaultTableModel dm = (DefaultTableModel)Flow.getModel();
                dm.getDataVector().removeAllElements();
                DefaultTableModel dm1 = (DefaultTableModel)FlowDefinition.getModel();
                dm1.getDataVector().removeAllElements();
                  Flow.setDefaultRenderer(Object.class, new KarmaTableCellRenderer());
                  for (int a=0;a<30;a++)
                    flowTableModel.insertRow(Flow.getRowCount(),new Object[]{""});
        FlowDefinition.setDefaultRenderer(Object.class, new KarmaTableCellRenderer());
        for (int a=0;a<30;a++)
        flowTableModelDef.insertRow(FlowDefinition.getRowCount(),new Object[]{""});
         
        }



    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:

            String base         =   org.karma.helper.projectInfo.base;
            String ext          =   org.karma.helper.projectInfo.language;
            String langName          =   org.karma.helper.projectInfo.languageName;
            
            LinkedHashMap hashMap = new LinkedHashMap();
            for (int a=0;a<Flow.getModel().getRowCount();a++)
            {
                //if (!Flow.getModel().getValueAt(a,1).equals(null))
                //{
                try
                {if (!Flow.getModel().getValueAt(a,1).equals(null))
                 {
                    hashMap.put(Flow.getModel().getValueAt(a,0)+" : "+Flow.getModel().getValueAt(a,1),Flow.getModel().getValueAt(a,2));
                 }
                }
                catch(Exception e){}
                    
                //}
            }
            LinkedHashMap hashMap1 = new LinkedHashMap();
              for (int a=0;a<FlowDefinition.getModel().getRowCount();a++)
            {
                //if (!Flow.getModel().getValueAt(a,1).equals(null))
                //{
                try
                {if (!FlowDefinition.getModel().getValueAt(a,1).equals(null))
                 {
                    hashMap1.put(FlowDefinition.getModel().getValueAt(a,0),FlowDefinition.getModel().getValueAt(a,1));
                 }
                }
                catch(Exception e){}

                //}
            }
        
            (new ManualFlowGraph(null,true,hashMap,hashMap1,receivingCode)).setVisible(true);
            



    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
      
         JFileChooser c = new JFileChooser();
       //  BASE64Encoder encoder = new BASE64Encoder();
       org.bouncycastle.util.encoders.Base64Encoder encoder = new org.bouncycastle.util.encoders.Base64Encoder();
        DesEncrypter encrypter = new DesEncrypter();//FIX !!!!
      int rVal = c.showSaveDialog(this);
      if (rVal == JFileChooser.APPROVE_OPTION) {
          String output = "";

          for (int a=0;a<Flow.getModel().getRowCount();a++)
            {
              

                if (Flow.getModel().getValueAt(a,0)!=null&&
                    Flow.getModel().getValueAt(a,1)!=null&&
                    Flow.getModel().getValueAt(a,2)!=null)

                try {
                     String output1="";
                    output1 = "";
                    
                    //FIX
                            //new String(encoder.encode((Flow.getModel().getValueAt(a, 0).toString()).getBytes(),a,0,Flow.getModel().getValueAt(a, 0).toString()).getBytes()));

/*    += new String(encoder.encode((Flow.getModel().getValueAt(a, 0).toString()).getBytes())) +
                             "," + new String(encoder.encode((Flow.getModel().getValueAt(a, 1).toString()).getBytes())) +
                             "," + new String(encoder.encode((Flow.getModel().getValueAt(a, 2).toString()).getBytes()));*/
                            output1=output1.replace("\n", "");
                            output = output+output1+"\n";

                    //}
                } catch (Exception ex) {
                    Exceptions.printStackTrace(ex);
                }   //}

            }
          output = output+"<Definitions>\n";

          //Definitions
                    for (int a=0;a<FlowDefinition.getModel().getRowCount();a++)
            {


                if (FlowDefinition.getModel().getValueAt(a,0)!=null&&
                    FlowDefinition.getModel().getValueAt(a,1)!=null)

                try {
                     String output1="";
                     
                     //FIX
                    /*output1      += new String(encoder.encode((FlowDefinition.getModel().getValueAt(a, 0).toString()).getBytes())) +
                             "," +  new String(encoder.encode((FlowDefinition.getModel().getValueAt(a, 1).toString()).getBytes()));

                            output1=output1.replace("\n", "");
                            output = output+output1+"\n"; */

                    //}
                } catch (Exception ex) {
                    Exceptions.printStackTrace(ex);
                }   //}

            }






            try {
                FileWriter fstream = new FileWriter(c.getSelectedFile());
                BufferedWriter out = new BufferedWriter(fstream);
                out.write(output);
                out.close();
            } catch (IOException ex) {
                Exceptions.printStackTrace(ex);
            }

          
      }
      if (rVal == JFileChooser.CANCEL_OPTION) {
       
      }


    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        (new ImporterOptions(null,true)).setVisible(true);

    }//GEN-LAST:event_jButton4ActionPerformed

    private void FlowMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FlowMouseClicked
        // TODO add your handling code here:
//if (receivingCode!=null)
//{
       try
       {
          String fullpathto = Flow.getValueAt(Flow.getSelectedRow(),2).toString();
          fullpathto = fullpathto.substring(org.karma.helper.projectInfo.base.length(),fullpathto.length());
          System.out.println("=>"+fullpathto);
          searchJTree sJT = new searchJTree();
          sJT.selectNode(sJT.doit(org.karma.helper.GlobalComponents.buglist,fullpathto),org.karma.helper.GlobalComponents.buglist);
          int line = Integer.parseInt(Flow.getValueAt(Flow.getSelectedRow(),0).toString())-1;
          Document doc = receivingCode.getDocument();
          javax.swing.text.Element elem = doc.getDefaultRootElement();
          receivingCode.setCaretPosition(elem.getElement(line).getStartOffset());
       }
       catch(Exception e){System.out.println(""+e);}
//}
    }//GEN-LAST:event_FlowMouseClicked

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
         try { ((DefaultTableModel)(FlowDefinition.getModel())).removeRow(FlowDefinition.getSelectedRow());}
        catch(Exception e){}
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:

        try
        {
        AddDefinitionDlg FD = new AddDefinitionDlg(null,true, FlowDefinition.getValueAt(FlowDefinition.getSelectedRow(),0).toString());
        FD.DefTextArea.setText(FlowDefinition.getValueAt(FlowDefinition.getSelectedRow(),1).toString());
        FD.addDef.setEnabled(false);
        FD.setVisible(true);
        }
        catch(Exception e){}

    }//GEN-LAST:event_jButton7ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTable Flow;
    public static javax.swing.JTable FlowDefinition;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
    /**
     * Gets default instance. Do not use directly: reserved for *.settings files only,
     * i.e. deserialization routines; otherwise you could get a non-deserialized instance.
     * To obtain the singleton instance, use {@link #findInstance}.
     */
    public static synchronized FlowNotesTopComponent getDefault() {
        if (instance == null) {
            instance = new FlowNotesTopComponent();
        }
        return instance;
    }

    /**
     * Obtain the FlowNotesTopComponent instance. Never call {@link #getDefault} directly!
     */
    public static synchronized FlowNotesTopComponent findInstance() {
        TopComponent win = WindowManager.getDefault().findTopComponent(PREFERRED_ID);
        if (win == null) {
            Logger.getLogger(FlowNotesTopComponent.class.getName()).warning(
                    "Cannot find " + PREFERRED_ID + " component. It will not be located properly in the window system.");
            return getDefault();
        }
        if (win instanceof FlowNotesTopComponent) {
            return (FlowNotesTopComponent) win;
        }
        Logger.getLogger(FlowNotesTopComponent.class.getName()).warning(
                "There seem to be multiple components with the '" + PREFERRED_ID
                + "' ID. That is a potential source of errors and unexpected behavior.");
        return getDefault();
    }

    @Override
    public int getPersistenceType() {
        return TopComponent.PERSISTENCE_ALWAYS;
    }

    @Override
    public void componentOpened() {
        // TODO add custom code on component opening
    }

    @Override
    public void componentClosed() {
        // TODO add custom code on component closing
    }

    void writeProperties(java.util.Properties p) {
        // better to version settings since initial version as advocated at
        // http://wiki.apidesign.org/wiki/PropertyFiles
        p.setProperty("version", "1.0");
        // TODO store your settings
    }

    Object readProperties(java.util.Properties p) {
        if (instance == null) {
            instance = this;
        }
        instance.readPropertiesImpl(p);
        return instance;
    }

    private void readPropertiesImpl(java.util.Properties p) {
        String version = p.getProperty("version");
        // TODO read your settings according to their version
    }

    @Override
    protected String preferredID() {
        return PREFERRED_ID;
    }
}
