/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ImporterOptions.java
 *
 * Created on Jun 5, 2011, 12:30:22 AM
 */

package FlowDiags;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.BufferedReader;
import java.io.DataInputStream;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStreamReader;
import javax.swing.JFileChooser;
import javax.swing.table.DefaultTableModel;
import org.openide.util.Exceptions;

/**
 *
 * @author Manos
 */
public class ImporterOptions extends javax.swing.JDialog {

    /** Creates new form ImporterOptions */
    public ImporterOptions(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        Dimension screenDim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation((screenDim.width-this.getWidth())/2,(screenDim.height-this.getHeight())/2);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, org.openide.util.NbBundle.getMessage(ImporterOptions.class, "ImporterOptions.jPanel1.border.title"), javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 0, 12))); // NOI18N

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FlowDiags/note.gif"))); // NOI18N
        jButton1.setText(org.openide.util.NbBundle.getMessage(ImporterOptions.class, "ImporterOptions.jButton1.text")); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon("/Users/Manos/Downloads/debugger-16x16.png")); // NOI18N
        jButton2.setText(org.openide.util.NbBundle.getMessage(ImporterOptions.class, "ImporterOptions.jButton2.text")); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jButton2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jButton1))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jButton1)
                .add(15, 15, 15)
                .add(jButton2)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
                this.dispose();
                // TODO add your handling code here:

            JFileChooser c = new JFileChooser();
            
            
          //  org.bouncycastle.util.encoders.BASE64Decoder decoder = new org.bouncycastle.util.encoders.BASE64Decoder();
      int rVal = c.showOpenDialog(this);
      if (rVal == JFileChooser.APPROVE_OPTION) {
          FileInputStream fstream = null;
            try {
                fstream = new FileInputStream(c.getSelectedFile());
            } catch (FileNotFoundException ex) {
                Exceptions.printStackTrace(ex);
            }
            // Get the object of DataInputStream
            DataInputStream in = new DataInputStream(fstream);
            BufferedReader br = new BufferedReader(new InputStreamReader(in));
              String strLine;
            try {

                DefaultTableModel dm = (DefaultTableModel)FlowNotesTopComponent.Flow.getModel();
                dm.getDataVector().removeAllElements();
                DefaultTableModel dm1 = (DefaultTableModel)FlowNotesTopComponent.FlowDefinition.getModel();
                dm1.getDataVector().removeAllElements();

                int rowCount=0;
                int rowCount1=0;
                boolean Def = false;
                while ((strLine = br.readLine()) != null) {
                    // Print the content on the console
                   if (strLine.equals("<Definitions>"))
                   {Def=true;continue;}

                   if(Def)
                   {
                    String[] backOn = strLine.split(",");
                    FlowNotesTopComponent.flowTableModelDef.insertRow(rowCount1,new Object[]
                    {
                      //  FIX new String(decoder.decodeBuffer(backOn[0])),
                       // new String(decoder.decodeBuffer(backOn[1]))
                         backOn[0],
                        backOn[1]
                            
                     
                    });
                     rowCount1++;
                   }

                   else
                   {
                    String[] backOn = strLine.split(",");
                    FlowNotesTopComponent.flowTableModel.insertRow(rowCount,new Object[]
                    {
                      // FIX  new String(decoder.decodeBuffer(backOn[0])),
                      //  new String(decoder.decodeBuffer(backOn[1])),
                      //  new String(decoder.decodeBuffer(backOn[2]))
                     
                      backOn[0],
                      backOn[1],
                     backOn[2]
                    });

                    rowCount++;
                   }



                }
            } catch (IOException ex) {
                Exceptions.printStackTrace(ex);
            }
            try {
                in.close();
            } catch (IOException ex) {
                Exceptions.printStackTrace(ex);
            }

      }




    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        (new ImportBackTrace(null,true)).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ImporterOptions dialog = new ImporterOptions(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

}
