/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * InspectorDlg.java
 *
 * Created on Jun 2, 2013, 10:31:17 PM
 */
package FlowDiags;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JEditorPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.Document;
import org.karma.helper.KarmaTableCellRenderer;
import org.karma.helper.searchJTree;

/**
 *
 * @author Manos
 */
public class InspectorDlg extends javax.swing.JDialog {
public String fileToOpen = "";
public int line = -1;
public static final String[] columnNames = {"Name", "File","Relationship","Line"};
public static DefaultTableModel RefTableModel;

    /** Creates new form InspectorDlg */
    public InspectorDlg(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
            this.setAlwaysOnTop(true);
        final Toolkit toolkit = Toolkit.getDefaultToolkit();
        final Dimension screenSize = toolkit.getScreenSize();
        final int x = (screenSize.width - this.getWidth()) / 2;
        final int y = (screenSize.height - this.getHeight()) / 2;
        this.setLocation(x, y);
        initComponents();
        ReferenceList.setBackground( null );
           RefTableModel = new DefaultTableModel(null,columnNames);
        ReferenceList.setModel(RefTableModel);

        //Set the size so it looks good
        //TableColumn col = ReferenceList.getColumnModel().getColumn(0);
        //col.setPreferredWidth(ReferenceList.getWidth()-(25/100)*ReferenceList.getWidth());
        //Decorative things
        ReferenceList.setShowHorizontalLines(false);
        ReferenceList.setShowVerticalLines(true);
        ReferenceList.setGridColor(Color.lightGray);
        ReferenceList.setDefaultRenderer(Object.class, new KarmaTableCellRenderer());
  
        
        

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backPanel = new javax.swing.JPanel();
        InspectorPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        definitionText = new javax.swing.JTextArea();
        addButton = new javax.swing.JButton();
        gotoButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        ReferenceList = new javax.swing.JTable();
        keywordText = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        backPanel.setLayout(new java.awt.BorderLayout());

        InspectorPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, org.openide.util.NbBundle.getMessage(InspectorDlg.class, "InspectorDlg.InspectorPanel.border.title"), javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 0, 12))); // NOI18N

        jLabel1.setFont(jLabel1.getFont().deriveFont(jLabel1.getFont().getSize()-1f));
        jLabel1.setText(org.openide.util.NbBundle.getMessage(InspectorDlg.class, "InspectorDlg.jLabel1.text")); // NOI18N

        jLabel2.setFont(jLabel2.getFont().deriveFont(jLabel2.getFont().getSize()-1f));
        jLabel2.setText(org.openide.util.NbBundle.getMessage(InspectorDlg.class, "InspectorDlg.jLabel2.text")); // NOI18N

        definitionText.setColumns(20);
        definitionText.setLineWrap(true);
        definitionText.setRows(5);
        jScrollPane1.setViewportView(definitionText);

        addButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FlowDiags/separator_grey.png"))); // NOI18N
        addButton.setText(org.openide.util.NbBundle.getMessage(InspectorDlg.class, "InspectorDlg.addButton.text")); // NOI18N
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        gotoButton.setFont(gotoButton.getFont().deriveFont(gotoButton.getFont().getSize()-1f));
        gotoButton.setText(org.openide.util.NbBundle.getMessage(InspectorDlg.class, "InspectorDlg.gotoButton.text")); // NOI18N
        gotoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gotoButtonActionPerformed(evt);
            }
        });

        jLabel3.setFont(jLabel3.getFont().deriveFont(jLabel3.getFont().getSize()-1f));
        jLabel3.setText(org.openide.util.NbBundle.getMessage(InspectorDlg.class, "InspectorDlg.jLabel3.text")); // NOI18N

        ReferenceList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        ReferenceList.setEnabled(false);
        ReferenceList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ReferenceListMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(ReferenceList);

        keywordText.setText(org.openide.util.NbBundle.getMessage(InspectorDlg.class, "InspectorDlg.keywordText.text")); // NOI18N
        keywordText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keywordTextActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout InspectorPanelLayout = new org.jdesktop.layout.GroupLayout(InspectorPanel);
        InspectorPanel.setLayout(InspectorPanelLayout);
        InspectorPanelLayout.setHorizontalGroup(
            InspectorPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(InspectorPanelLayout.createSequentialGroup()
                .add(20, 20, 20)
                .add(jLabel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 548, Short.MAX_VALUE)
                .addContainerGap(177, Short.MAX_VALUE))
            .add(InspectorPanelLayout.createSequentialGroup()
                .add(20, 20, 20)
                .add(jLabel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 548, Short.MAX_VALUE)
                .addContainerGap(177, Short.MAX_VALUE))
            .add(InspectorPanelLayout.createSequentialGroup()
                .add(20, 20, 20)
                .add(jLabel3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 548, Short.MAX_VALUE)
                .addContainerGap(177, Short.MAX_VALUE))
            .add(org.jdesktop.layout.GroupLayout.TRAILING, InspectorPanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(jScrollPane2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 705, Short.MAX_VALUE)
                .addContainerGap())
            .add(org.jdesktop.layout.GroupLayout.TRAILING, InspectorPanelLayout.createSequentialGroup()
                .add(20, 20, 20)
                .add(InspectorPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(InspectorPanelLayout.createSequentialGroup()
                        .add(gotoButton)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 415, Short.MAX_VALUE)
                        .add(addButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 157, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 705, Short.MAX_VALUE))
                .add(20, 20, 20))
            .add(InspectorPanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(keywordText, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 705, Short.MAX_VALUE)
                .addContainerGap())
        );
        InspectorPanelLayout.setVerticalGroup(
            InspectorPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(InspectorPanelLayout.createSequentialGroup()
                .add(jLabel1)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(keywordText, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(4, 4, 4)
                .add(jLabel2)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 135, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(InspectorPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(addButton)
                    .add(gotoButton))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabel3)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jScrollPane2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                .addContainerGap())
        );

        backPanel.add(InspectorPanel, java.awt.BorderLayout.CENTER);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(backPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 757, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(backPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 419, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        // TODO add your handling code here:
        
       
        this.dispose();
    }//GEN-LAST:event_addButtonActionPerformed

    public static JEditorPane receivingCode=null;
    private void gotoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gotoButtonActionPerformed
        // TODO add your handling code here:
     boolean checkNull = true;  
        
      try
       {
          String fullpathto =fileToOpen;
          String slash = System.getProperty("file.separator");
          fullpathto = slash+fullpathto.substring(org.karma.helper.projectInfo.base.length()-1,fullpathto.length());
          searchJTree sJT = new searchJTree();
          sJT.selectNode(sJT.doit(org.karma.helper.GlobalComponents.buglist,fullpathto),org.karma.helper.GlobalComponents.buglist);          
          
          
          Document doc = receivingCode.getDocument();
          
          javax.swing.text.Element elem = doc.getDefaultRootElement();
          
          
          receivingCode.setCaretPosition(elem.getElement(line-1).getStartOffset());
          
          
       }
       catch(Exception e){System.out.println(""+e);}
          
       
       
          
    }//GEN-LAST:event_gotoButtonActionPerformed

    private void ReferenceListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ReferenceListMouseClicked
        // TODO add your handling code here:
         try
       {
          String fullpathto = ReferenceList.getValueAt(ReferenceList.getSelectedRow(),1).toString();
          fullpathto = fullpathto.substring(org.karma.helper.projectInfo.base.length()-2,fullpathto.length());
          searchJTree sJT = new searchJTree();
          sJT.selectNode(sJT.doit(org.karma.helper.GlobalComponents.buglist,fullpathto),org.karma.helper.GlobalComponents.buglist);
          
          int line = Integer.parseInt(ReferenceList.getValueAt(ReferenceList.getSelectedRow(),3).toString())-1;
          Document doc = receivingCode.getDocument();
          javax.swing.text.Element elem = doc.getDefaultRootElement();
          
          
          
          try {receivingCode.setCaretPosition(elem.getElement(line).getStartOffset());}
          catch(Exception e){}
         
       }
       catch(Exception e){System.out.println(""+e);}
        
        
    }//GEN-LAST:event_ReferenceListMouseClicked

    private void keywordTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keywordTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_keywordTextActionPerformed

    /**
     * @param args the command line arguments
     */
 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel InspectorPanel;
    public javax.swing.JTable ReferenceList;
    private javax.swing.JButton addButton;
    private javax.swing.JPanel backPanel;
    public javax.swing.JTextArea definitionText;
    private javax.swing.JButton gotoButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JTextField keywordText;
    // End of variables declaration//GEN-END:variables
}
