/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CommentsLinesGraph.java
 *
 * Created on May 14, 2010, 3:49:56 PM
 */

package org.karma.visual;

/**
 *
 * @author Manos
 */
public class CommentsLinesGraph extends javax.swing.JDialog {

    /** Creates new form CommentsLinesGraph */
   public CommentsLinesGraph(java.awt.Frame parent, boolean modal,String base,String ext)  {
        super(parent, false);
        this.setAlwaysOnTop(true);
        initComponents();
        CommentsLinesGraphWorker plotCC = new CommentsLinesGraphWorker(base,CLGraph,ext);
        plotCC.start();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        CLGraph = new javax.swing.JPanel();
        loading = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(CommentsLinesGraph.class, "CommentsLinesGraph.jPanel3.border.title"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        jLabel1.setText(org.openide.util.NbBundle.getMessage(CommentsLinesGraph.class, "CommentsLinesGraph.jLabel1.text")); // NOI18N

        org.jdesktop.layout.GroupLayout jPanel3Layout = new org.jdesktop.layout.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel1)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel3Layout.createSequentialGroup()
                .add(jLabel1)
                .addContainerGap())
        );

        CLGraph.setBackground(new java.awt.Color(255, 255, 255));

        loading.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/karma/visual/35-0.gif"))); // NOI18N
        loading.setText(org.openide.util.NbBundle.getMessage(CommentsLinesGraph.class, "CommentsLinesGraph.loading.text")); // NOI18N

        org.jdesktop.layout.GroupLayout CLGraphLayout = new org.jdesktop.layout.GroupLayout(CLGraph);
        CLGraph.setLayout(CLGraphLayout);
        CLGraphLayout.setHorizontalGroup(
            CLGraphLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, CLGraphLayout.createSequentialGroup()
                .addContainerGap(114, Short.MAX_VALUE)
                .add(loading)
                .add(167, 167, 167))
        );
        CLGraphLayout.setVerticalGroup(
            CLGraphLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(CLGraphLayout.createSequentialGroup()
                .add(54, 54, 54)
                .add(loading, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 121, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(74, Short.MAX_VALUE))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .add(CLGraph, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(jPanel3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(CLGraph, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CLGraph;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel loading;
    // End of variables declaration//GEN-END:variables

}
