/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CyclomaticCGraph.java
 *
 * Created on May 9, 2010, 12:11:51 PM
 */

package org.karma.visual;

/**
 *
 * @author Manos
 */
public class CyclomaticCGraph extends javax.swing.JDialog {

    /** Creates new form CyclomaticCGraph */
    public CyclomaticCGraph(java.awt.Frame parent, boolean modal,String base,String ext)  {
        super(parent, false);
        this.setAlwaysOnTop(true);

        initComponents();
     //   CCGraphWorker graph = new CCGraphWorker();
     //   graph.doit(base,CCGraph,ext);
        CCGraphWorker plotCC = new CCGraphWorker(base,CCGraph,ext);
        plotCC.start();
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        keyword = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        CCGraph = new javax.swing.JPanel();
        loading = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(CyclomaticCGraph.class, "CyclomaticCGraph.jPanel3.border.title"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 10));
        jLabel1.setText(org.openide.util.NbBundle.getMessage(CyclomaticCGraph.class, "CyclomaticCGraph.jLabel1.text")); // NOI18N

        keyword.setFont(new java.awt.Font("Lucida Grande", 0, 10));
        keyword.setForeground(new java.awt.Color(0, 51, 51));
        keyword.setText(org.openide.util.NbBundle.getMessage(CyclomaticCGraph.class, "CyclomaticCGraph.keyword.text")); // NOI18N

        org.jdesktop.layout.GroupLayout jPanel3Layout = new org.jdesktop.layout.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel1)
                    .add(keyword, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 667, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel3Layout.createSequentialGroup()
                .add(jLabel1)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(keyword, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 13, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        CCGraph.setBackground(new java.awt.Color(255, 255, 255));

        loading.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/karma/visual/35-0.gif"))); // NOI18N
        loading.setText(org.openide.util.NbBundle.getMessage(CyclomaticCGraph.class, "CyclomaticCGraph.loading.text")); // NOI18N

        org.jdesktop.layout.GroupLayout CCGraphLayout = new org.jdesktop.layout.GroupLayout(CCGraph);
        CCGraph.setLayout(CCGraphLayout);
        CCGraphLayout.setHorizontalGroup(
            CCGraphLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(CCGraphLayout.createSequentialGroup()
                .add(274, 274, 274)
                .add(loading)
                .addContainerGap(266, Short.MAX_VALUE))
        );
        CCGraphLayout.setVerticalGroup(
            CCGraphLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(CCGraphLayout.createSequentialGroup()
                .add(55, 55, 55)
                .add(loading, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 121, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(188, Short.MAX_VALUE))
        );

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(CCGraph, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(CCGraph, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(jPanel3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 60, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CCGraph;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel keyword;
    private javax.swing.JLabel loading;
    // End of variables declaration//GEN-END:variables

}
