/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.karma.visual;

import java.awt.Component;
import java.util.Calendar;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JTree;
import javax.swing.UIManager;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeCellRenderer;
import javax.swing.tree.DefaultTreeModel;
import org.openide.util.NbBundle;
import org.openide.windows.TopComponent;
import org.openide.windows.WindowManager;
import org.openide.util.ImageUtilities;
import org.netbeans.api.settings.ConvertAsProperties;

/**
 * Top component which displays something.
 */
@ConvertAsProperties(dtd = "-//org.karma.visual//FileVisiCode//EN",
autostore = false)
public final class FileVisiCodeTopComponent extends TopComponent {

    private static FileVisiCodeTopComponent instance;
    /** path to the icon used by the component and its open action */
    static final String ICON_PATH = "org/karma/visual/1273159664_edit-mathematics.png";
    private static final String PREFERRED_ID = "FileVisiCodeTopComponent";

 

    public FileVisiCodeTopComponent() {
        initComponents();
        setName(NbBundle.getMessage(FileVisiCodeTopComponent.class, "CTL_FileVisiCodeTopComponent"));
        setToolTipText(NbBundle.getMessage(FileVisiCodeTopComponent.class, "HINT_FileVisiCodeTopComponent"));
        setIcon(ImageUtilities.loadImage(ICON_PATH, true));
        putClientProperty(TopComponent.PROP_MAXIMIZATION_DISABLED, Boolean.TRUE);
        putClientProperty(TopComponent.PROP_UNDOCKING_DISABLED, Boolean.TRUE);
        putClientProperty(TopComponent.PROP_KEEP_PREFERRED_SIZE_WHEN_SLIDED_IN, Boolean.TRUE);



         DefaultMutableTreeNode root_node = new DefaultMutableTreeNode("There is no active file");
    DefaultTreeModel treeModel = new DefaultTreeModel(root_node);
    this.metrics.setModel(treeModel);

  DefaultTreeCellRenderer dft =  new DefaultTreeCellRenderer(){
      public Component getTreeCellRendererComponent(final JTree tree,Object value,boolean sel,boolean expanded,boolean leaf,int row,boolean hasFocus){
        JLabel label = (JLabel)super.getTreeCellRendererComponent(tree,value,sel,expanded,leaf,row,hasFocus);
            if(((DefaultMutableTreeNode)value).isRoot()) label.setIcon(new ImageIcon(super.getClass().getResource("graph-home.png")));
            if(((DefaultMutableTreeNode)value).isLeaf()) label.setIcon(new ImageIcon(super.getClass().getResource("point.png")));
            return label;
                                                                            }
    };
    //dft.setBackgroundNonSelectionColor(new java.awt.Color(255, 255, 20));
    
    //UIManager.put("Tree.leafIcon", leafIcon);

   // ImageIcon leafIcon = new ImageIcon(super.getClass().getResource("bug-file.png"));
   // dft.setLeafIcon(leafIcon);

    metrics.setCellRenderer(dft);

//metrics.setEditable(false);
metrics.setSelectionModel(null);
org.karma.helper.GlobalComponents.metrics = metrics;

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        metrics = new javax.swing.JTree();

        jScrollPane1.setViewportView(metrics);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTree metrics;
    // End of variables declaration//GEN-END:variables
    /**
     * Gets default instance. Do not use directly: reserved for *.settings files only,
     * i.e. deserialization routines; otherwise you could get a non-deserialized instance.
     * To obtain the singleton instance, use {@link #findInstance}.
     */
    public static synchronized FileVisiCodeTopComponent getDefault() {
        if (instance == null) {
            instance = new FileVisiCodeTopComponent();
        }
        return instance;
    }

    /**
     * Obtain the FileVisiCodeTopComponent instance. Never call {@link #getDefault} directly!
     */
    public static synchronized FileVisiCodeTopComponent findInstance() {
        TopComponent win = WindowManager.getDefault().findTopComponent(PREFERRED_ID);
        if (win == null) {
            Logger.getLogger(FileVisiCodeTopComponent.class.getName()).warning(
                    "Cannot find " + PREFERRED_ID + " component. It will not be located properly in the window system.");
            return getDefault();
        }
        if (win instanceof FileVisiCodeTopComponent) {
            return (FileVisiCodeTopComponent) win;
        }
        Logger.getLogger(FileVisiCodeTopComponent.class.getName()).warning(
                "There seem to be multiple components with the '" + PREFERRED_ID
                + "' ID. That is a potential source of errors and unexpected behavior.");
        return getDefault();
    }

    @Override
    public int getPersistenceType() {
        return TopComponent.PERSISTENCE_ALWAYS;
    }

    @Override
    public void componentOpened() {
        // TODO add custom code on component opening
    }

    @Override
    public void componentClosed() {
        // TODO add custom code on component closing
    }

    void writeProperties(java.util.Properties p) {
        // better to version settings since initial version as advocated at
        // http://wiki.apidesign.org/wiki/PropertyFiles
        p.setProperty("version", "1.0");
        // TODO store your settings
    }

    Object readProperties(java.util.Properties p) {
        if (instance == null) {
            instance = this;
        }
        instance.readPropertiesImpl(p);
        return instance;
    }

    private void readPropertiesImpl(java.util.Properties p) {
        String version = p.getProperty("version");
        // TODO read your settings according to their version
    }

    @Override
    protected String preferredID() {
        return PREFERRED_ID;
    }
}
