/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ManualFlowGraph.java
 *
 * Created on May 30, 2011, 7:25:19 PM
 */

package org.karma.visual;

import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.LinkedHashMap;
import javax.swing.JEditorPane;
import javax.swing.JFileChooser;
import javax.swing.JMenuItem;
import javax.swing.JPopupMenu;
import org.openide.util.Exceptions;
import prefuse.Display;
import prefuse.data.Tree;

/**
 *
 * @author Manos
 */
public class FollowCallsGraph extends javax.swing.JDialog {
    /** Creates new form ManualFlowGraph */
public static Display tmpD=null;
  public FollowCallsGraph(java.awt.Frame parent, boolean modal,Tree hashMap,JEditorPane jdp) {
        super(parent, false);
        this.setAlwaysOnTop(true);
        initComponents();
        //ManualFlowGraphWorker(JPanel jdlW,LinkedHashMap hashMapW,LinkedHashMap hashMapW1,JEditorPane jdpW)
        //ManualFlowGraphWorker plotCC = new ManualFlowGraphWorker(KeyCloud,hashMap,hashMap1,jdp);
        FollowCallsGraphWorker plotCC = new FollowCallsGraphWorker(KeyCloud,hashMap,jdp);
        
        plotCC.start();

     

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        keyword = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        Inclusion = new javax.swing.JPanel();
        KeyCloud = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(FollowCallsGraph.class, "ManualFlowGraph.jPanel3.border.title"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        jLabel1.setText(org.openide.util.NbBundle.getMessage(FollowCallsGraph.class, "ManualFlowGraph.jLabel1.text")); // NOI18N

        keyword.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        keyword.setForeground(new java.awt.Color(0, 51, 51));
        keyword.setText(org.openide.util.NbBundle.getMessage(FollowCallsGraph.class, "ManualFlowGraph.keyword.text")); // NOI18N

        jButton1.setText(org.openide.util.NbBundle.getMessage(FollowCallsGraph.class, "ManualFlowGraph.jButton1.text")); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel3Layout = new org.jdesktop.layout.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel3Layout.createSequentialGroup()
                        .add(jLabel1)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 395, Short.MAX_VALUE)
                        .add(jButton1))
                    .add(jPanel3Layout.createSequentialGroup()
                        .add(93, 93, 93)
                        .add(keyword, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 722, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel3Layout.createSequentialGroup()
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1)
                    .add(jButton1))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(keyword, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 13, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );

        Inclusion.setBackground(new java.awt.Color(255, 255, 255));
        Inclusion.setLayout(new javax.swing.BoxLayout(Inclusion, javax.swing.BoxLayout.LINE_AXIS));

        KeyCloud.setBackground(new java.awt.Color(255, 255, 255));
        KeyCloud.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                KeyCloudMouseClicked(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/karma/visual/35-0.gif"))); // NOI18N
        jLabel2.setText(org.openide.util.NbBundle.getMessage(FollowCallsGraph.class, "ManualFlowGraph.jLabel2.text")); // NOI18N

        org.jdesktop.layout.GroupLayout KeyCloudLayout = new org.jdesktop.layout.GroupLayout(KeyCloud);
        KeyCloud.setLayout(KeyCloudLayout);
        KeyCloudLayout.setHorizontalGroup(
            KeyCloudLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, KeyCloudLayout.createSequentialGroup()
                .add(368, 368, 368)
                .add(jLabel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(325, 325, 325))
        );
        KeyCloudLayout.setVerticalGroup(
            KeyCloudLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(KeyCloudLayout.createSequentialGroup()
                .add(94, 94, 94)
                .add(jLabel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(123, 123, 123))
        );

        Inclusion.add(KeyCloud);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(Inclusion, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 854, Short.MAX_VALUE)
            .add(jPanel3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(jPanel3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(0, 0, 0)
                .add(Inclusion, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 283, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void KeyCloudMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_KeyCloudMouseClicked
        // TODO add your handling code here:

           
    }//GEN-LAST:event_KeyCloudMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
                // TODO add your handling code here:
          JFileChooser c = new JFileChooser();

      int rVal = c.showSaveDialog(this);
      if (rVal == JFileChooser.APPROVE_OPTION)
      {FileOutputStream fstream = null;
            try {
                 fstream = new FileOutputStream(c.getSelectedFile());

            } catch (IOException ex) {
                Exceptions.printStackTrace(ex);
            }
      tmpD.saveImage(fstream, "PNG", 1);
      //c.getSelectedFile()
      }
    }//GEN-LAST:event_jButton1ActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Inclusion;
    private javax.swing.JPanel KeyCloud;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel keyword;
    // End of variables declaration//GEN-END:variables

}
