/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

package org.karma.buglist;

import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.io.File;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.Set;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JEditorPane;
import javax.swing.JLabel;
import javax.swing.JScrollPane;
import javax.swing.JTree;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeCellRenderer;
import javax.swing.tree.DefaultTreeModel;
import org.openide.util.NbBundle;
import org.openide.windows.TopComponent;
import org.openide.windows.WindowManager;
import org.openide.util.ImageUtilities;
import org.netbeans.api.settings.ConvertAsProperties;
import org.karma.SourceViewer.SourceViewerTopComponent;
import org.karma.helper.ReportExportHandler;
import org.karma.helper.SourceViewHandler;
import org.karma.helper.SummaryViewHandler;
import org.karma.helper.searchJTree;







/**
 * Top component which displays something.
 */
@ConvertAsProperties(
    dtd="-//org.karma.buglist//buglist//EN",
    autostore=false
)
public  class buglistTopComponent extends TopComponent  {

    private static buglistTopComponent instance;
    /** path to the icon used by the component and its open action */
    static final String ICON_PATH = "org/karma/buglist/1246385891_folder_explore.png";

    private static final String PREFERRED_ID = "buglistTopComponent";

    public static ArrayList<String> bugsFiles = new ArrayList();
    public static ArrayList<String> bugsLines = new ArrayList();
    public static ArrayList<String> Confidence = new ArrayList();

    public buglistTopComponent() {

       
       
        
        
        if (!(SourceViewerTopComponent.getRegistry().getOpened().size()>0))
        {
            SourceViewerTopComponent sv = new SourceViewerTopComponent();
            sv.open();
            sv.requestActive();
        }

        
        
        initComponents();      
        //BugList Cell Renderer

    DefaultMutableTreeNode root_node = new DefaultMutableTreeNode("Choose Source Base");
    DefaultTreeModel treeModel = new DefaultTreeModel(root_node);
    buglistTopComponent.BugTree.setModel(treeModel);

  DefaultTreeCellRenderer dft =  new DefaultTreeCellRenderer(){
            @Override
      public Component getTreeCellRendererComponent(final JTree tree,Object value, boolean sel,boolean expanded,boolean leaf,int row,boolean hasFocus){
          
        JLabel label = (JLabel)super.getTreeCellRendererComponent(tree,value,sel,expanded,leaf,row,hasFocus);
        label.setBackground(new Color(255,255,204));
                
        
            if(((DefaultMutableTreeNode)value).isRoot()) label.setIcon(new ImageIcon(super.getClass().getResource("home-root.png")));
            return label;
                                                                            }
    };
    dft.setBackgroundNonSelectionColor(new java.awt.Color(255, 255, 204));


    ImageIcon leafIcon = new ImageIcon(super.getClass().getResource("bug-files.png"));
    dft.setLeafIcon(leafIcon);
    
    BugTree.setCellRenderer(dft);


        setName(NbBundle.getMessage(buglistTopComponent.class, "CTL_buglistTopComponent"));
        setToolTipText(NbBundle.getMessage(buglistTopComponent.class, "HINT_buglistTopComponent"));
        setIcon(ImageUtilities.loadImage(ICON_PATH, true));
	putClientProperty(TopComponent.PROP_UNDOCKING_DISABLED, Boolean.TRUE);
        org.karma.helper.GlobalComponents.buglist = BugTree;
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        BugTree = new javax.swing.JTree();
        jToolBar1 = new javax.swing.JToolBar();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        jLabel1 = new javax.swing.JLabel();
        SearchFilename = new javax.swing.JTextField();

        setMaximumSize(new java.awt.Dimension(300, 300));
        setPreferredSize(new java.awt.Dimension(233, 300));

        BugTree.setBackground(new java.awt.Color(255, 255, 204));
        BugTree.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BugTreeMouseClicked(evt);
            }
        });
        BugTree.addTreeSelectionListener(new javax.swing.event.TreeSelectionListener() {
            public void valueChanged(javax.swing.event.TreeSelectionEvent evt) {
                BugTreeValueChanged(evt);
            }
        });
        BugTree.addHierarchyListener(new java.awt.event.HierarchyListener() {
            public void hierarchyChanged(java.awt.event.HierarchyEvent evt) {
                BugTreeHierarchyChanged(evt);
            }
        });
        BugTree.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                BugTreePropertyChange(evt);
            }
        });
        jScrollPane1.setViewportView(BugTree);

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);
        jToolBar1.add(jSeparator1);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 12));
        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(buglistTopComponent.class, "buglistTopComponent.jLabel1.text")); // NOI18N
        jToolBar1.add(jLabel1);

        SearchFilename.setFont(new java.awt.Font("Lucida Grande", 0, 10));
        SearchFilename.setText(org.openide.util.NbBundle.getMessage(buglistTopComponent.class, "buglistTopComponent.SearchFilename.text")); // NOI18N
        SearchFilename.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchFilenameActionPerformed(evt);
            }
        });
        SearchFilename.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                SearchFilenameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                SearchFilenameFocusLost(evt);
            }
        });
        SearchFilename.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                SearchFilenameKeyPressed(evt);
            }
        });
        jToolBar1.add(SearchFilename);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    
    private void BugTreeValueChanged(javax.swing.event.TreeSelectionEvent evt) {//GEN-FIRST:event_BugTreeValueChanged
        // TODO add your handling code here:

       
        openEditor();

        



    }//GEN-LAST:event_BugTreeValueChanged

    private void SearchFilenameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchFilenameActionPerformed
        // TODO add your handling code here:
      
    }//GEN-LAST:event_SearchFilenameActionPerformed

    private void SearchFilenameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_SearchFilenameKeyPressed
        // TODO add your handling code here:
          String fullpathto =".*"+SearchFilename.getText()+".*";
                            searchJTree sJT = new searchJTree();
                            DefaultMutableTreeNode dmtn = sJT.doitRegex(org.karma.helper.GlobalComponents.buglist,fullpathto);
                            if (dmtn == null){SearchFilename.setForeground(Color.red);}
                            else {SearchFilename.setForeground(Color.black);}
                            sJT.selectNode(dmtn,org.karma.helper.GlobalComponents.buglist);
    }//GEN-LAST:event_SearchFilenameKeyPressed

    
    
    private void openEditor()
    {
	    org.karma.helper.projectInfo.StartUpCount++;
    
    //Bring source code up with bug lines
        if (bugsFiles.size()>0)
        
        {

   

        String ThePath = "";
            try {ThePath =BugTree.getSelectionPath().toString().replaceAll(", ", System.getProperty("file.separator"));}
            catch(Exception e){BugTree.getSelectionPath();}
        ThePath = ThePath.replaceAll(System.getProperty("file.separator")+System.getProperty("file.separator"),System.getProperty("file.separator"));
        ThePath = ThePath.replaceAll("\\[","");
        ThePath = ThePath.replaceAll("\\]","");
        
        ThePath = org.karma.helper.projectInfo.base.substring(0,org.karma.helper.projectInfo.base.lastIndexOf(System.getProperty("file.separator")))+""+ThePath;
        
        String fileName = "";
         //System.out.println(ThePath+"<--");
            
        //Just in case we click the ROOT
        try {fileName = ThePath.substring(0,ThePath.lastIndexOf("("));
        File canonicalFilePath = new File(fileName);
        fileName = canonicalFilePath.getCanonicalPath();
        
        }
                
        catch (Exception e){System.out.println(ThePath);fileName =ThePath;}
        //System.out.println(fileName);
        boolean foundIt = false;
        int foundItAt=0;
        for (int goThrough=0;goThrough<bugsFiles.size();goThrough++)
        {
            if(bugsFiles.get(goThrough).equalsIgnoreCase(fileName))
            {
            
            foundIt = true;
            break;
            }
            foundItAt++;
        }

        if (foundIt)
        {
            SourceViewerTopComponent sv=null;
            boolean AlreadyOpen = false;
        Set<TopComponent> openViewersSet = SourceViewerTopComponent.getRegistry().getOpened();
         Iterator iter = openViewersSet.iterator();
         
         while (iter.hasNext())
         {
           TopComponent currentTopComponent =   (TopComponent)iter.next();
            if (currentTopComponent.getToolTipText().equals(fileName))
            {
               sv = (SourceViewerTopComponent)currentTopComponent;
             currentTopComponent.requestActive();
             AlreadyOpen = true;
             break;
            }
         }

    if (AlreadyOpen==false)
    {
        sv = new SourceViewerTopComponent();
        sv.open();
       

        String titleBar = fileName.substring(fileName.lastIndexOf(System.getProperty("file.separator"))+1);
        sv.setHtmlDisplayName(titleBar);
        
        sv.requestActive();
        
        sv.setToolTipText(fileName);

        sv.SourceCode.setText("Loading "+fileName+"..........");        
        bugsLines.get(foundItAt).split("-");
        if (new File(fileName).isFile())
        {

        
        SourceViewHandler SVH = 
                new  SourceViewHandler (
                org.karma.helper.GlobalComponents.metrics,
                sv.SourceCode,
                fileName,bugsLines.get(foundItAt).split("-")[0],
                Confidence.get(foundItAt));


        SVH.start();
    
    

        
        
        
        
        }
        FlowDiags.FlowNotesTopComponent.receivingCode=sv.SourceCode;
        FlowDiags.InspectorDlg.receivingCode=sv.SourceCode;

        
        }
  SummaryViewHandler SSH =
                new  SummaryViewHandler (
                sv.Bugs,
                fileName,bugsLines.get(foundItAt).split("-")[0],
                Confidence.get(foundItAt));

        SSH.start();
         
       FlowDiags.FlowNotesTopComponent.receivingCode=sv.SourceCode;

       

        

        }



        }
    
    
    }
    
    
    
    
    
    
    
    
    
    
    private void SearchFilenameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_SearchFilenameFocusGained
        // TODO add your handling code here:
          SearchFilename.setBackground(new Color(0xFFFFCC));
    }//GEN-LAST:event_SearchFilenameFocusGained

    private void SearchFilenameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_SearchFilenameFocusLost
        // TODO add your handling code here:
          SearchFilename.setBackground(new Color(0xFFFFFF));
    }//GEN-LAST:event_SearchFilenameFocusLost

    private void BugTreeHierarchyChanged(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_BugTreeHierarchyChanged
        // TODO add your handling code here:
        
    }//GEN-LAST:event_BugTreeHierarchyChanged

    private void BugTreePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_BugTreePropertyChange
        // TODO add your handling code here:
      
        
    }//GEN-LAST:event_BugTreePropertyChange

    private void BugTreeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BugTreeMouseClicked
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_BugTreeMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTree BugTree;
    private javax.swing.JTextField SearchFilename;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
    /**
     * Gets default instance. Do not use directly: reserved for *.settings files only,
     * i.e. deserialization routines; otherwise you could get a non-deserialized instance.
     * To obtain the singleton instance, use {@link #findInstance}.
     */
    public static synchronized buglistTopComponent getDefault() {
        if (instance == null) {
            instance = new buglistTopComponent();
        }
        return instance;
    }

    /**
     * Obtain the buglistTopComponent instance. Never call {@link #getDefault} directly!
     */
    public static synchronized buglistTopComponent findInstance() {
        TopComponent win = WindowManager.getDefault().findTopComponent(PREFERRED_ID);
        if (win == null) {
            Logger.getLogger(buglistTopComponent.class.getName()).warning(
                    "Cannot find " + PREFERRED_ID + " component. It will not be located properly in the window system.");
            return getDefault();
        }
        if (win instanceof buglistTopComponent) {
            return (buglistTopComponent) win;
        }
        Logger.getLogger(buglistTopComponent.class.getName()).warning(
                "There seem to be multiple components with the '" + PREFERRED_ID +
                "' ID. That is a potential source of errors and unexpected behavior.");
        return getDefault();
    }

    @Override
    public int getPersistenceType() {
        return TopComponent.PERSISTENCE_ALWAYS;
    }

    @Override
    public void componentOpened() {
        // TODO add custom code on component opening
    }

    @Override
    public void componentClosed() {
        // TODO add custom code on component closing
    }

    void writeProperties(java.util.Properties p) {
        // better to version settings since initial version as advocated at
        // http://wiki.apidesign.org/wiki/PropertyFiles
        p.setProperty("version", "1.0");
        // TODO store your settings
    }

    Object readProperties(java.util.Properties p) {
        buglistTopComponent singleton = buglistTopComponent.getDefault();
        singleton.readPropertiesImpl(p);
        return singleton;
    }

    private void readPropertiesImpl(java.util.Properties p) {
        String version = p.getProperty("version");
        // TODO read your settings according to their version
    }

    @Override
    protected String preferredID() {
        return PREFERRED_ID;
    }



  
}



