/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * KarmaController.java
 *
 * Created on Jul 23, 2009, 8:03:41 PM
 */

package org.karma.toolbar;

import java.awt.Color;
import java.io.File;
import java.util.ArrayList;
import java.util.prefs.Preferences;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import org.karma.helper.ParseConfig;
import org.karma.helper.ConsolePrint;

import org.karma.buglist.buglistTopComponent;
import org.karma.engineinfo.EngineInfoTopComponent;
import org.karma.SourceViewer.SourceViewerTopComponent;
import org.karma.analyser.AnalysisWorker;
import org.karma.helper.projectInfo;


/**
 *
 * @author Manos
 */
public class KarmaController extends javax.swing.JPanel {
public static double Sensitivity= 0.7;
    /** Creates new form KarmaController */
    public KarmaController() {
        

        initComponents();
       
        
        heatscan.setSelected(org.karma.helper.projectInfo.heatscan);
        Sensor.setFocusPainted(false);
        Sensor.setBorderPainted(false);

         StartKarma.setBorder(null);
        StopKarma.setBorder(null);
        Sensor.setBorder(null);
        
        
        StartKarma.setEnabled(false);
        StopKarma.setEnabled(false);
        //  new org.karma.helper.ConfigWindowTopComponent.ConfigWindowTopComponent();
       ParseConfig.checkForConfig();
       if (!(ParseConfig.checkForNeeded())) { JOptionPane.showMessageDialog(null, "There was a problem with the config file, within the Configuration panel\nreview, save and restart Karma.\n\nIf the problem persists, remove \"KarmaHam.config\" and restart.", "", 1, new ImageIcon(super.getClass().getResource("warning.png")));}

       ArrayList LanguageItems = ParseConfig.extractLanguageAndExtension();
         for (int a = 0; a < LanguageItems.size(); ++a)
            {
            String[] itemsToAdd = LanguageItems.get(a).toString().split("=");
            if (itemsToAdd.length != 2) continue; Language.addItem(itemsToAdd[0].trim());
            }
       RegEx.setText("(\\s\\*\\s)|(\\/\\*)|(^\\\".*\\\"$)|(#)");
       Sensor.setText(((int)(Sensitivity*100))+"%");
       //Check SignatureFile
       


    }
    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        StartKarma = new javax.swing.JButton();
        CodeBase = new javax.swing.JButton();
        Language = new javax.swing.JComboBox();
        checkRegEx = new javax.swing.JCheckBox();
        RegEx = new javax.swing.JTextField();
        Sensor = new javax.swing.JButton();
        StopKarma = new javax.swing.JButton();
        heatscan = new javax.swing.JCheckBox();
        isSignatures = new javax.swing.JCheckBox();

        setPreferredSize(new java.awt.Dimension(854, 49));

        StartKarma.setForeground(new java.awt.Color(255, 255, 255));
        StartKarma.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/karma/toolbar/Play Green Button.png"))); // NOI18N
        StartKarma.setText(org.openide.util.NbBundle.getMessage(KarmaController.class, "KarmaController.StartKarma.text")); // NOI18N
        StartKarma.setBorder(null);
        StartKarma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StartKarmaActionPerformed(evt);
            }
        });

        CodeBase.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/karma/toolbar/openproject.png"))); // NOI18N
        CodeBase.setText(org.openide.util.NbBundle.getMessage(KarmaController.class, "KarmaController.CodeBase.text")); // NOI18N
        CodeBase.setBorder(null);
        CodeBase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CodeBaseActionPerformed(evt);
            }
        });

        Language.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        Language.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Choose Language" }));
        Language.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LanguageActionPerformed(evt);
            }
        });

        checkRegEx.setFont(new java.awt.Font("Lucida Grande", 0, 11)); // NOI18N
        checkRegEx.setForeground(new java.awt.Color(255, 255, 255));
        checkRegEx.setText(org.openide.util.NbBundle.getMessage(KarmaController.class, "KarmaController.checkRegEx.text")); // NOI18N
        checkRegEx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkRegExActionPerformed(evt);
            }
        });

        RegEx.setBackground(new java.awt.Color(226, 225, 225));
        RegEx.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        RegEx.setForeground(new java.awt.Color(153, 153, 153));
        RegEx.setText(org.openide.util.NbBundle.getMessage(KarmaController.class, "KarmaController.RegEx.text")); // NOI18N
        RegEx.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RegExMouseClicked(evt);
            }
        });
        RegEx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegExActionPerformed(evt);
            }
        });

        Sensor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/karma/toolbar/1248624405_stock_hyperlink-target.png"))); // NOI18N
        Sensor.setText(org.openide.util.NbBundle.getMessage(KarmaController.class, "KarmaController.Sensor.text")); // NOI18N
        Sensor.setToolTipText(org.openide.util.NbBundle.getMessage(KarmaController.class, "KarmaController.Sensor.toolTipText")); // NOI18N
        Sensor.setBorder(null);
        Sensor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SensorActionPerformed(evt);
            }
        });

        StopKarma.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/karma/toolbar/Stop Green Button.png"))); // NOI18N
        StopKarma.setText(org.openide.util.NbBundle.getMessage(KarmaController.class, "KarmaController.StopKarma.text")); // NOI18N
        StopKarma.setBorder(null);
        StopKarma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StopKarmaActionPerformed(evt);
            }
        });

        heatscan.setFont(new java.awt.Font("Lucida Grande", 0, 11)); // NOI18N
        heatscan.setForeground(new java.awt.Color(255, 255, 204));
        heatscan.setText(org.openide.util.NbBundle.getMessage(KarmaController.class, "KarmaController.heatscan.text")); // NOI18N
        heatscan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                heatscanActionPerformed(evt);
            }
        });

        isSignatures.setFont(new java.awt.Font("Lucida Grande", 0, 11)); // NOI18N
        isSignatures.setForeground(new java.awt.Color(255, 255, 255));
        isSignatures.setText(org.openide.util.NbBundle.getMessage(KarmaController.class, "KarmaController.isSignatures.text")); // NOI18N
        isSignatures.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isSignaturesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(StartKarma)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(StopKarma, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CodeBase, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Language, 0, 150, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkRegEx)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RegEx, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Sensor)
                .addGap(18, 18, 18)
                .addComponent(heatscan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(isSignatures)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(checkRegEx)
                        .addComponent(RegEx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Sensor)
                        .addComponent(heatscan)
                        .addComponent(isSignatures))
                    .addComponent(Language, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CodeBase, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                    .addComponent(StartKarma, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                    .addComponent(StopKarma, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void RegExMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegExMouseClicked
        // TODO add your handling code here:
      
}//GEN-LAST:event_RegExMouseClicked

    private void RegExActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegExActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RegExActionPerformed

    private void checkRegExActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkRegExActionPerformed
        // TODO add your handling code here:

    if(checkRegEx.isSelected())
    {
        RegEx.setBackground(new Color(255,255,204));
        RegEx.setForeground(new Color(0,0,0));
         ConsolePrint.reportToConsole("Exclude lines with: "+RegEx.getText());
    }

    else   
    {
        RegEx.setBackground(new Color(226,225,225));
        RegEx.setForeground(new Color(153,153,153));
        ConsolePrint.reportToConsole("RegEx Excluder is DISABLED");

    }
    }//GEN-LAST:event_checkRegExActionPerformed

    private void LanguageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LanguageActionPerformed
        // TODO add your handling code here:
        ConsolePrint.reportToConsole("Language SET to: "+Language.getSelectedItem().toString());
    }//GEN-LAST:event_LanguageActionPerformed

    Preferences prefs;
    private void CodeBaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CodeBaseActionPerformed
        // TODO add your handling code here:
        
        JFileChooser chooser = new JFileChooser();
        chooser.setCurrentDirectory(new File("."));
        chooser.setDialogTitle("Pick Source Base Directory");
        chooser.setFileSelectionMode(1);
        chooser.setAcceptAllFileFilterUsed(false);
        prefs = Preferences.userNodeForPackage(this.getClass());
        String lastOutputDir = prefs.get("LAST_SCAN_DIR", "");
        if (!lastOutputDir.equals("")) {chooser.setCurrentDirectory(new File(lastOutputDir));}

    if (chooser.showOpenDialog(this) == 0)  {
      CodeBase.setToolTipText(chooser.getSelectedFile() + "");
      ConsolePrint.reportToConsole("Target is at:"+chooser.getSelectedFile() + "");
      StartKarma.setEnabled(true);
        CodeBase.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/karma/toolbar/openprojectset.png")));
        CodeBase.setBorder(null);
      String DisplayCodeBase = chooser.getSelectedFile() + "";
      prefs.put("LAST_SCAN_DIR", chooser.getSelectedFile().getParent());
       
       
      

      DisplayCodeBase = DisplayCodeBase.substring(DisplayCodeBase.lastIndexOf(System.getProperty("file.separator")) + 1);
      DefaultMutableTreeNode root_node = new DefaultMutableTreeNode(DisplayCodeBase);
      DefaultTreeModel treeModel = new DefaultTreeModel(root_node);
      buglistTopComponent.BugTree.setModel(treeModel);
     org.karma.helper.projectInfo.rootDirectory = CodeBase.getToolTipText();
                                            }
    }//GEN-LAST:event_CodeBaseActionPerformed

AnalysisWorker AW;
    private void StartKarmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartKarmaActionPerformed
        // TODO add your handling code here:
        String ExcludeThese = "";
        if (checkRegEx.isSelected()){ ExcludeThese = RegEx.getText();}

      if (Language.getSelectedItem().toString().equals("Choose Language"))  JOptionPane.showMessageDialog(null, "KARMA ERROR\n Please, Specify a Programming language!", "", 1, new ImageIcon(super.getClass().getResource("warning.png")));
      else if (org.karma.helper.projectInfo.currentKarma.equalsIgnoreCase(""))  JOptionPane.showMessageDialog(null, "KARMA ERROR\n Please, Select Karma!", "", 1, new ImageIcon(super.getClass().getResource("warning.png")));
      else
      {

          ConsolePrint.reportToConsole("Karma Scan Started!");
          StartKarma.setEnabled(false);
          StopKarma.setEnabled(true);
          org.karma.buglist.buglistTopComponent.bugsFiles = new ArrayList();
          org.karma.buglist.buglistTopComponent.bugsLines = new ArrayList();
          org.karma.buglist.buglistTopComponent.Confidence = new ArrayList();
          org.karma.helper.projectInfo.sensitivity = Sensitivity;
          org.karma.helper.projectInfo.languageName = Language.getSelectedItem().toString();
          AW = new AnalysisWorker
                  (
                  "Massive_C",
                  Language.getSelectedItem().toString(),
                  CodeBase.getToolTipText() ,
                  ExcludeThese,
                  Sensitivity,
                  buglistTopComponent.BugTree,
                  EngineInfoTopComponent.ScanningProgress,
                  StartKarma,
                  StopKarma,
                  org.karma.buglist.buglistTopComponent.bugsFiles,
                  org.karma.buglist.buglistTopComponent.bugsLines,
                  org.karma.buglist.buglistTopComponent.Confidence
                  );
          AW.start();
          
         
          //
           
      }

    }//GEN-LAST:event_StartKarmaActionPerformed

    private void SensorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SensorActionPerformed
        // TODO add your handling code here:
        new Sensitivity(null, true).show();
    }//GEN-LAST:event_SensorActionPerformed

    private void heatscanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_heatscanActionPerformed
        // TODO add your handling code here:

        if(heatscan.isSelected()) {org.karma.helper.projectInfo.heatscan = true;}
        else { org.karma.helper.projectInfo.heatscan = false; }
    }//GEN-LAST:event_heatscanActionPerformed

    private void StopKarmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StopKarmaActionPerformed
        // TODO add your handling code here:

        AW.stop();
        StopKarma.setEnabled(false);
        StartKarma.setEnabled(true);
        ConsolePrint.reportToConsole("Scan canceled!");
        EngineInfoTopComponent.ScanningProgress.setValue(EngineInfoTopComponent.ScanningProgress.getMaximum());


    }//GEN-LAST:event_StopKarmaActionPerformed

    private void isSignaturesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isSignaturesActionPerformed
        // TODO add your handling code here:
        
        if (isSignatures.isSelected())
            org.karma.helper.projectInfo.IsSignatureOn = true;
        else
            org.karma.helper.projectInfo.IsSignatureOn = false;
        
         
    }//GEN-LAST:event_isSignaturesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton CodeBase;
    public static javax.swing.JComboBox Language;
    public static javax.swing.JTextField RegEx;
    public static javax.swing.JButton Sensor;
    public javax.swing.JButton StartKarma;
    public static javax.swing.JButton StopKarma;
    public static javax.swing.JCheckBox checkRegEx;
    public static javax.swing.JCheckBox heatscan;
    public static javax.swing.JCheckBox isSignatures;
    // End of variables declaration//GEN-END:variables

}
