/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Sensitivity.java
 *
 * Created on Jul 26, 2009, 5:24:15 PM
 */

package org.karma.toolbar;

import java.awt.Dimension;
import java.awt.Toolkit;



/**
 *
 * @author Manos
 */
public class Sensitivity extends javax.swing.JDialog {

    /** Creates new form Sensitivity */
    public Sensitivity(java.awt.Frame parent, boolean modal)
    {
        super(parent, modal);
        initComponents();
        AccuracySensor.setValue       ((int)(KarmaController.Sensitivity*100));
        KarmaController.Sensor.setText((int)(KarmaController.Sensitivity*100)+"%");
        Dimension screenDim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation((screenDim.width-this.getWidth())/2,(screenDim.height-this.getHeight())/2);
        comment.setText("Here you set the accuracy of the analyser. The classifier has set some probability of something being a bug, so you can filter the threshold.");
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        AccuracySensor = new javax.swing.JSlider();
        jScrollPane1 = new javax.swing.JScrollPane();
        comment = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, org.openide.util.NbBundle.getMessage(Sensitivity.class, "Sensitivity.jPanel1.border.title"), javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 0, 11))); // NOI18N

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/karma/helper/target.png"))); // NOI18N
        jLabel1.setText(org.openide.util.NbBundle.getMessage(Sensitivity.class, "Sensitivity.jLabel1.text")); // NOI18N

        AccuracySensor.setMajorTickSpacing(5);
        AccuracySensor.setMaximum(99);
        AccuracySensor.setMinorTickSpacing(1);
        AccuracySensor.setPaintLabels(true);
        AccuracySensor.setPaintTicks(true);
        AccuracySensor.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                AccuracySensorStateChanged(evt);
            }
        });
        AccuracySensor.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                AccuracySensorPropertyChange(evt);
            }
        });
        AccuracySensor.addVetoableChangeListener(new java.beans.VetoableChangeListener() {
            public void vetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {
                AccuracySensorVetoableChange(evt);
            }
        });

        jScrollPane1.setBorder(null);

        comment.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        comment.setFont(new java.awt.Font("Lucida Grande", 0, 11));
        comment.setForeground(new java.awt.Color(51, 51, 51));
        jScrollPane1.setViewportView(comment);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 559, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AccuracySensor, javax.swing.GroupLayout.DEFAULT_SIZE, 511, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(AccuracySensor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AccuracySensorPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_AccuracySensorPropertyChange
        // TODO add your handling code here:
      
       
    }//GEN-LAST:event_AccuracySensorPropertyChange

    private void AccuracySensorVetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {//GEN-FIRST:event_AccuracySensorVetoableChange
        // TODO add your handling code here:
        
    }//GEN-LAST:event_AccuracySensorVetoableChange

    private void AccuracySensorStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_AccuracySensorStateChanged
        // TODO add your handling code here:
         KarmaController.Sensitivity = ((double)AccuracySensor.getValue())/100;
         KarmaController.Sensor.setText((int)(KarmaController.Sensitivity*100)+"%");
         KarmaController.Sensor.updateUI();
    }//GEN-LAST:event_AccuracySensorStateChanged

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Sensitivity dialog = new Sensitivity(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSlider AccuracySensor;
    private javax.swing.JTextPane comment;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

}
